### ISSUE TITLE
[Request] Update AWS tutorial with better screen captures

### ISSUE THREAD

**Issue by dedemorton** [elastic/ingest-docs#103]
## Description

There were some problems with the data shown in the screen captures in the AWS tutorial added by https://github.com/elastic/observability-docs/pull/2106. When these problems are resolved, we need to update the screen captures to show better data. Specifically we need to:

~- [ ] Add a screen capture of the infrastructure app that shows EC2 info.~
~- [ ] Update the EC2 overview dashboard to show better data.~

=> After discussion, it has been agreed to remove the screenshots for maintainability purposes.

## Collaboration

- The docs team will lead producing the content

**Contact Person:**
@tommyers-elastic

**Comment by alaudazzi** [comment]
@dedemorton 
I tried to build some context around this ticket by reading through https://github.com/elastic/observability-docs/pull/2106, but I'm not sure all these screenshots are actually required. Let's sync before I start working on this.

**Comment by dedemorton** [comment]
Looking at the comments in the related PR, I remember that there were some issues with the data that was displayed back then showing messages that didn't make sense. I added some filters to remove the weird data, but created an issue to remind myself to go back and update the screenshots later.
 
 If you don't think the screenshots are required, you should remove them. If you want to keep the screenshots, you should update them. It's your call.

**Comment by alaudazzi** [comment]
Thank you @dedemorton 
For maintenance purposes, I tend to keep a minimalist approach, the same that I applied to the new tutorials [Firehose](https://www.elastic.co/guide/en/observability/current/monitor-aws-firehose.html) and [ESF](https://www.elastic.co/guide/en/observability/current/monitor-aws-esf.html). I'll keep this ticket open until I've cleaned up the screenshots.
