### ISSUE TITLE
Add documentation to cover the container flow. 

### ISSUE THREAD

**Issue by merlixelastic** [elastic/ingest-docs#1075]
### Description

We discovered a scenario where deploying Elastic agent with Fleet server integration need to have certificate to connect to Kibana.
This is setup apparently with variable KIBANA_CA or KIBANA_FLEET_CA.
I believe the code (reference in resources below) is related to the installation of Elastic agent with Fleet server on Kubernetes or docker.

### Resources

The code  related to this is [here](https://github.com/elastic/elastic-agent/blob/302ec2cc10f306132a908ccc93c2e7f79cb1c429/internal/pkg/agent/cmd/container.go#L527)

I'm not seeing mention of setting up certificate between Elastic agent to Kibana in our documentation [here](https://www.elastic.co/guide/en/fleet/current/add-fleet-server-mixed.html) and [there](https://www.elastic.co/guide/en/fleet/current/secure-connections.html#secure-connections).

This was discovered when we investigated error:
`Kibana fetch policy failed: http GET request to https://kibana-multi:5601/api/fleet/agent_policies fails: fail to execute the HTTP GET request: Get "https://kibana-multi:5601/api/fleet/agent_policies": x509: certificate signed by unknown authority.`

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @merlixelastic 

**Stakeholders:** @lucabelluccini

**Comment by lucabelluccini** [comment]
This item has been discussed on 3rd June with Julien & Pierre

**Comment by kilfoyle** [comment]
Thanks for reporting this @merlixelastic and for the clarifications @lucabelluccini.

So I think we need to:

1. Update the [Deployment models](https://www.elastic.co/guide/en/fleet/current/fleet-deployment-models.html) page to cover the steps for setting up Fleet Server on Kubernetes.
2. Mention on that same page that managed Elastic Agent can be set up in ECK, with a link to [the relevant docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elastic-agent-fleet.html).
3. Update the [default port assignments](https://www.elastic.co/guide/en/fleet/current/add-fleet-server-mixed.html#default-port-assignments-mixed). It seems the only change needed is to remove the "Elastic Agent -> Fleet" entry.

@michel-laterman could you perhaps provide the steps for #1? I have no idea about the K8s setup at all, so if you don't mind putting something in a draft document I'd be happy to port that into the [Deployment models](https://www.elastic.co/guide/en/fleet/current/fleet-deployment-models.html) page. 

I'll look after 2 and 3 shortly.

@nimarezainia just for your awareness.

**Comment by kilfoyle** [comment]
Regaring requirement 1, @nimarezainia and I discussed this and are thinking that we can update the Elastic Agent install instruction pages for Kubernetes and for Docker, to add the additional settings required to run agent as a Fleet Server. I've opened a PR with the proposed changes: https://github.com/elastic/ingest-docs/pull/1184

@michel-laterman I'm guessing a bit at what I think the settings are so please take a look and let us know if anything needs fixing.

**Comment by michel-laterman** [comment]
We have documentation for container env vars that fleet-server uses during bootstrapping; however these are under the elastic-agent install instructions: https://www.elastic.co/guide/en/fleet/current/agent-environment-variables.html#env-prepare-kibana-for-fleet

I think we can re-organize some pages to make it more clear that we expect an end user to only deploy a fleet-server as an agent component and better utilize the agent installation instructions.

Additionally we should go over the env vars, i'm not certain if `KIBANA_FLEET_SETUP` still applies to agents in containers anymore

**Comment by kilfoyle** [comment]
Thanks @michel-laterman. I'll wait for your suggestions on this, as well as for https://github.com/elastic/ingest-docs/pull/1184 "Add Fleet Server install steps on K8s and Docker". 

If/when the Elastic Agent install pages have everything required to install Fleet Server, we probably just need to mention that somewhere in the [Deployment models](https://www.elastic.co/guide/en/fleet/current/fleet-deployment-models.html) section.

**Comment by lucabelluccini** [comment]
Regarding the `KIBANA_FLEET*` env vars, please note we had users (see issue below) where the enrollment was failing.

**Comment by kilfoyle** [comment]
Looks like we're nearing completion on this:

 - [ ] **1.** Add steps for setting up Fleet Server on Kubernetes:
     - [x] **a.** Add the Fleet Server setup steps to the Docker and Kubernetes pages [Run Elastic Agent in a container](https://www.elastic.co/guide/en/fleet/master/elastic-agent-container.html#_step_4_run_the_elastic_agent_image) and [Run Elastic Agent on Kubernetes managed by Fleet](https://www.elastic.co/guide/en/fleet/master/running-on-kubernetes-managed-by-fleet.html#_step_3_enroll_elastic_agent_to_the_policy)
     - See https://github.com/elastic/ingest-docs/pull/1184 
      - [ ] **b.** Add a "Docker and Kubernetes" section to the the [Deployment models](https://www.elastic.co/guide/en/fleet/current/fleet-deployment-models.html) page with links to the above.
      - See https://github.com/elastic/ingest-docs/pull/1334
 - [x] **2.** Mention on that same page that managed Elastic Agent can be set up in ECK, with a link to [the relevant docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elastic-agent-fleet.html).
     - See https://github.com/elastic/ingest-docs/pull/1176
 - [ ] **3.** From Michel: We should go over the env vars, i'm not certain if `KIBANA_FLEET_SETUP` still applies to agents in containers anymore
 - [x] **4.** Update the [default port assignments](https://www.elastic.co/guide/en/fleet/current/add-fleet-server-mixed.html#default-port-assignments-mixed) to remove the "Elastic Agent -> Fleet" entry.
     - This has been discussed separately in Slack, and I understand from that discussion that there is a scenario (maybe during initial setup?) where Agent talks directly to Fleet/Kibana. So I think we should leave this as is. Let me know anyone if you disagree.

---

@michel-laterman  Can you please help with number 3, and also review my small PR for number 1?

@merlixelastic, @lucabelluccini, @nimarezainia  Let me know if you think we're missing anything.

**Comment by michel-laterman** [comment]
`KIBANA_FLEET_SETUP ` has been removed for a while: https://github.com/elastic/elastic-agent/issues/2910

We're missing some env vars in our public docs (as well as from the output of the container help command):
- `FLEET_FORCE` - same as the `--force flag`
- `ELASTIC_AGENT_CERT` & `ELASTIC_AGENT_CERT_KEY` - paths to mtls cert and key the agent will use to connect to fleet-server. (corresponding var for passphrase is missing)
- `FLEET_SERVER_CLIENT_AUTH` - set fleet-server mtls settings, one of: `none` (default), `optional`, `required`
- `FLEET_SERVER_ES_CERT` & `FLEET_SERVER_ES_CERT_KEY` - fleet-server -> es mTLS cert paths. (corresponding var for passphrase is missing)
- `FLEET_SERVER_INSECURE_HTTP` - expose fleet-server as an http server
- `FLEET_HEADER` - I think this one is headers the agent will send to fleet-server
- `FLEET_KIBANA_HEADER` - headers used when contacting Kibana
- `FLEET_SERVER_TIMEOUT` - how long elastic-agent will wait for fleet-server to checkin as healthy
- `FLEET_DAEMON_TIMEOUT` - how long fleet-server will wait during the bootstrap process for elastic-agent

**Comment by kilfoyle** [comment]
Nice catch @michel-laterman! I'll add the above env vars to the [docs page](https://www.elastic.co/guide/en/fleet/current/agent-environment-variables.html#env-prepare-kibana-for-fleet).

**Comment by kilfoyle** [comment]
@michel-laterman I've opened [this PR](https://github.com/elastic/ingest-docs/pull/1354) to add the missing settings. For easier reviewing, I've opened [this gdoc](https://docs.google.com/document/d/10NH4LMPZksG2R7-sd3lKbxms_-PZzxpy05z4kfna7NE/edit) and everyone from this issue should have access.

@nimarezainia FYI

**Comment by kilfoyle** [comment]
@merlixelastic and @lucabelluccini  I've just merged [this PR](https://github.com/elastic/ingest-docs/pull/1354) to add the environment variables for container setup that hadn't already been documented. That completes the list of "To dos" in [this comment](https://github.com/elastic/ingest-docs/pull/1354), so I think this issue can be closed now.

If we've missed anything, please let us know and I can open a new docs issue. Thanks!

And thanks @michel-laterman for the help on this!

**Comment by lucabelluccini** [comment]
Thank you @kilfoyle 

My only comment/follow up is @michel-laterman reports the code was removed https://github.com/elastic/elastic-agent/issues/2910, but we had a user hitting the error below when enrolling an Elastic Agent / Fleet Server on 8.13 on a container/kubernetes installation:
```
Kibana fetch policy failed: http GET request to https://kibana-multi:5601/api/fleet/agent_policies fails: fail to execute the HTTP GET request: Get "https://kibana-multi:5601/api/fleet/agent_policies": x509: certificate signed by unknown authority.
```

At this point I wonder if we should open a separate issue to investigate.

**Comment by kilfoyle** [comment]
> At this point I wonder if we should open a separate issue to investigate.

@lucabelluccini  It's a great question but it's not something I would know how to investigate, so I'd really appreciate if this could go into a separate issue in the ingest-dev repo.
