### ISSUE TITLE
Initial Ingest OTel collector docs for Elastic Agent

### ISSUE THREAD

**Issue by kilfoyle** [elastic/ingest-docs#1086]
From Bill: 

>We've been asked to push up the release of the OTel collector and to make onboarding available via the UI in 8.15.0.

>We'd like to start producing the initially internal docs for using the "OTel-mode" of Elastic Agent. In the beginning we just want to document basic (how to start OTel-mode, how to configure OTel, etc) usage but it'll probably expand out to several documents as we get closer to GA.

**Resources**
configuration: https://opentelemetry.io/docs/collector/configuration/
transforming: https://opentelemetry.io/docs/collector/transforming-telemetry/
architecture: https://opentelemetry.io/docs/collector/architecture/
deployment (agent): https://opentelemetry.io/docs/collector/deployment/agent/
Readme on using agent in otel mode: https://github.com/elastic/elastic-agent/blob/main/internal/pkg/otel/README.md?plain=1

To be visible only in the 8.15+ versions of the Fleet & Agent guide, starting at the 8.15 GA date (July 30).

Use Beta (`[preview]`) admonition:
`This functionality is in technical preview and may be changed or removed in a future release. Elastic will apply best effort to fix any issues, but features in technical preview are not subject to the support SLA of official GA features.`

**Comment by bmorelli25** [comment]
@kilfoyle have you seen https://github.com/elastic/opentelemetry-dev/issues/242? Does this issue cover all of the asks in that issue?

**Comment by strawgate** [comment]
documentation for troubleshooting onboarding flows should live in the onboarding guides, we can expand this out as desired

**Comment by kilfoyle** [comment]
Closed by https://github.com/elastic/ingest-docs/pull/1250
