### ISSUE TITLE
Update proxy config screencaps

### ISSUE THREAD

**Issue by kilfoyle** [elastic/ingest-docs#1102]
The beta label and warnings about remote Elasticsearch clusters not being supported are being removed from the Fleet UI via https://github.com/elastic/kibana/pull/184811. The screencaps in the corresponding [Proxy configuration docs](https://www.elastic.co/guide/en/fleet/8.13/fleet-agent-proxy-managed.html) need to be updated accordingly (see Cristina's [comment](https://github.com/elastic/ingest-dev/issues/3232#issuecomment-2149754789)).

Setting priority to "high" since customers are waiting on this.
Target: 8.15 (to match the UI PR)

**Comment by criamico** [comment]
@kilfoyle I think that we need to remove also the beta warning from this page: https://www.elastic.co/guide/en/fleet/8.13/fleet-agent-proxy-managed.html (under 4. Attach the proxy to the agent download source)

I couldn't find any beta warning related to proxy configs but I would appreciate if you could also take a look.
