### ISSUE TITLE
[Fleet]: Screenshot not updated for Integrations tab as config and API reference tab is not available.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#1103]
**Description:**
Screenshot not updated for Integrations tab as config and API reference tab is not available.

**Link:**
https://www.elastic.co/guide/en/observability/8.14/logs-metrics-get-started.html#view-data
https://www.elastic.co/guide/en/fleet/current/upgrade-integration.html#upgrade-integration-to-latest-version

**Actual Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/13a14c2b-d0fc-4745-99c7-77ad063b42d6)

**Expected Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/7f6e96cb-c528-4008-a394-5c40fcc8eb5e)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
FYI @kilfoyle

**Comment by amolnater-qasource** [comment]
Hi Team,

We have validated the updated docs at links:

- https://www.elastic.co/guide/en/observability/8.17/logs-metrics-get-started.html#view-data

**Screenshots:**
![Image](https://github.com/user-attachments/assets/ae3f4bf2-1dcb-493a-903a-38dff1fa62c1)


Hence, we are marking this issue as **QA:Validated**.

Thanks!!
