### ISSUE TITLE
[Fleet]: Screenshot not updated for Integrations tab as View Deployment details is visible.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#1104]
**Description:**
Screenshot not updated for Integrations tab as View Deployment link is visible.

**Link:**
https://www.elastic.co/guide/en/fleet/current/example-standalone-monitor-nginx-serverless.html#nginx-guide-add-integration-serverless

**Actual Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/8b895652-4e49-4e2a-850e-65affb6947b2)

**Expected Screenshot:**

![image](https://github.com/elastic/ingest-docs/assets/77374876/95596408-969c-4faf-904d-4a8c4e9b7247)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
FYI @kilfoyle

**Comment by amolnater-qasource** [comment]
Hi Team,

We have validated the updated docs at links:

- https://www.elastic.co/guide/en/fleet/current/example-standalone-monitor-nginx-serverless.html#nginx-guide-add-integration-serverless

**Screenshots:**
![Image](https://github.com/user-attachments/assets/c45f02fc-a369-4878-9b29-6e5e140a918e)


Hence, we are marking this issue as **QA:Validated**.

Thanks!!
