### ISSUE TITLE
[Fleet]: Diagnostics tab is missing under agents details tab in screenshots.

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/ingest-docs#1105]
**Description:**
Diagnostics tab is missing under agents details tab in screenshots.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/monitor-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/current/upgrade-elastic-agent.html

**Actual screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/101545338/03759719-269a-4172-b6ca-5092468cf87a)

**Expected Screenshot**
![image](https://github.com/elastic/ingest-docs/assets/101545338/05f4c03c-211e-4579-8915-6bde029799e3)

**Expected Result**
Diagnostics tab should display under agents details tab in screenshots.

**Comment by harshitgupta-qasource** [comment]
@amolnater-qasource Kindly review

**Comment by amolnater-qasource** [comment]
Secondary review for this ticket is Done.

**Comment by harshitgupta-qasource** [comment]
Hi Team,

We have validated the updated docs at links:

- https://www.elastic.co/guide/en/fleet/current/upgrade-elastic-agent.html#view-upgrade-status
- https://www.elastic.co/guide/en/fleet/current/monitor-elastic-agent.html#change-logging-level

**Screenshots:**
![Image](https://github.com/user-attachments/assets/b22a3655-d1af-4c67-8638-60d2261dfd52)
![Image](https://github.com/user-attachments/assets/cc994ff0-a8b1-486f-b41d-2260da462f2f)


Hence, we are marking this issue as **QA:Validated**.

Thanks!!
