### ISSUE TITLE
[Fleet]: Outdated screenshot for Discover tab is visible.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#1106]
**Description:**
Outdated screenshot for Discover tab is visible.

**Link:**
https://www.elastic.co/guide/en/fleet/current/example-standalone-monitor-nginx-serverless.html#nginx-guide-confirm-agent-data-serverless
https://www.elastic.co/guide/en/fleet/current/example-standalone-monitor-nginx.html

**Actual Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/84e49374-3f0c-4bef-89e5-614d6fe11df6)

**Expected Screenshot:**

![image](https://github.com/elastic/ingest-docs/assets/77374876/8efd28fd-2f3f-4411-be2d-f0adf9a60db0)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
FYI @kilfoyle

**Comment by amolnater-qasource** [comment]
Hi Team,

We have validated the updated docs at links:

- https://www.elastic.co/guide/en/fleet/current/example-standalone-monitor-nginx-serverless.html#nginx-guide-confirm-agent-data-serverless


**Screenshots:**
![Image](https://github.com/user-attachments/assets/5863f6a1-9871-4218-a115-314ff836e54d)

Hence, we are marking this issue as **QA:Validated**.

Thanks!!
