### ISSUE TITLE
[Fleet]: Screenshot not updated for Agents tab as uninstall tokens tab is missing.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#1108]
**Description:**
 Screenshot not updated for Agents tab as uninstall tokens tab is missing.

**Link:**
https://www.elastic.co/guide/en/fleet/current/example-standalone-monitor-nginx.html#nginx-guide-create-policy-ess

**Actual Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/943b4ff7-c29f-4687-93a4-94800297d705)

**Expected Screenshot:**

![image](https://github.com/elastic/ingest-docs/assets/77374876/21e34590-2617-401c-b4b2-bf305178ead8)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
FYI @kilfoyle

**Comment by amolnater-qasource** [comment]
Hi Team,

We have validated the updated docs at links:

- https://www.elastic.co/guide/en/fleet/current/example-standalone-monitor-nginx.html#nginx-guide-create-policy-ess

**Screenshot:**
![Image](https://github.com/user-attachments/assets/d3bf1a66-4636-4e93-b8f5-39e14f4d3921)


Hence, we are marking this issue as **QA:Validated**.

Thanks!!
