### ISSUE TITLE
[Fleet]: "#" not added with tickets of Fleet Server section under Release notes.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#1109]
**Description:**
"#" not added with tickets of Fleet Server section under Release notes.

**Link:**
https://www.elastic.co/guide/en/fleet/current/release-notes-8.14.0.html

**Actual Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/cb4d2a19-4c9f-457e-a40d-aeef132c7972)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
FYI @kilfoyle

**Comment by kilfoyle** [comment]
Thanks for reporting this! It should be fixed as soon as https://github.com/elastic/ingest-docs/pull/1112 merges.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have validated the updated docs at links:

- https://www.elastic.co/guide/en/fleet/current/release-notes-8.17.0.html

**Screenshot:**
![Image](https://github.com/user-attachments/assets/0175968a-46e5-49c8-81a1-37a3d70da47a)

Hence, we are closing this issue and marking as **QA:Validated**.

Thanks!!
