### ISSUE TITLE
Document policy tagging

### ISSUE THREAD

**Issue by kilfoyle** [elastic/ingest-docs#1134]
We'll need docs in the F&A Guide for policy tagging: https://github.com/elastic/kibana/issues/179915

**Comment by jlind23** [comment]
@kilfoyle according to your project board it looks like this issue has fallen into the cracks. Will it be ready for 8.15?

**Comment by kilfoyle** [comment]
@jlind23 Thanks for the prompt! I'll make sure this gets in for 8.15. Should get to it next week.
