### ISSUE TITLE
[REQUEST]: Document how to run Elastic Agent and Beats in containers with `--read-only` filesystems

### ISSUE THREAD

**Issue by ycombinator** [elastic/ingest-docs#1152]
### Description

Typically users who run Elastic Agent or Beats in containers do so with "normal" read/write filesystems.  However, some users may want to run these products in containers with read-only filesystems.  This is achieved by passing an additional `--read-only` CLI flag to the `docker run` command.

When Elastic Agent or Beats are run in containers with a read-only filesystem, users will get errors unless they also specify a mount path to a filesystem location where the products can write their internal state.  We need to document this scenario.

### Resources

https://github.com/elastic/ingest-dev/issues/3267#issuecomment-2196796778
https://github.com/elastic/elastic-agent/pull/4995#issuecomment-2192751402

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @blakerouse

**Comment by kilfoyle** [comment]
Thanks for opening this @ycombinator!

Beats docs PR: https://github.com/elastic/beats/pull/40092
Elastic Agent docs PR: https://github.com/elastic/ingest-docs/pull/1154

**Comment by kilfoyle** [comment]
I think this can be closed now:
 - Beats docs updated via https://github.com/elastic/beats/pull/40092
 - Elastic Agent docs updated via https://github.com/elastic/ingest-docs/pull/1154
