### ISSUE TITLE
[DOCS] Unprivileged mode docs review

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/ingest-docs#1197]
I've reviewed the page https://www.elastic.co/guide/en/fleet/8.15/elastic-agent-unprivileged.html#unprivileged-running

1) In the docs, we have:
<img width="814" alt="image" src="https://github.com/user-attachments/assets/4a1c1f37-2250-4e38-9c59-4140353486f1">

But the Fleet UI https://github.com/elastic/kibana/pull/184845 tells the opposite 
<img width="730" alt="image" src="https://github.com/user-attachments/assets/a6690dd2-360c-4c74-9de4-86966c6a7eac">

Afaik, `sudo` is always necessary as it will setup the systemd unit, which requires `sudo`.
But maybe I'm not up to date with the latests changes to such feature. Can we confirm which one of the 2 is right?

2) In the docs we have:
<img width="662" alt="image" src="https://github.com/user-attachments/assets/82053016-5881-419c-a30a-cb546e15a19b">

But it points to the section where you can change the permissions of the user and group of Elastic Agent at the bottom. 
I would expect instructions / cli commands to switch an Elastic Agent:
- From privileged to unprivileged
- From unprivileged to privileged

If it is not possible, we should clearly state it (I think the workaround would be un-enrolling and re-installing? Do we lose the state?)

3) The section `Agent and dashboard behaviors in unprivileged mode` only mentions logs errors and missing info in the dashboards, but we do not tell anything about the Elastic Agent reported status in the Fleet UI. Will it be degraded? Unhealthy?

Will the errors surface in the page below?
<img width="1227" alt="image" src="https://github.com/user-attachments/assets/7672522c-8928-430b-bfa6-9e777bb3f6d3">

4) Do we show the Elastic Agent is running as unprivileged in the Elastic Agent page?

5) Is there a cli command to know if the EA is running unprivileged?

**Comment by lucabelluccini** [comment]
Hello @kilfoyle, I've reviewed the page prior 8.15 release - some points need to be clarified by the engineers who worked on the feature I think

**Comment by kilfoyle** [comment]
Thanks @lucabelluccini.  I'll try to answer these as well as I can:

---
> (1) Afaik, sudo is always necessary as it will setup the systemd unit, which requires sudo.
But maybe I'm not up to date with the latests changes to such feature. Can we confirm which one of the 2 is right?

It's now possible to run agent without `sudo`. The warning is meant to indicate that when an agent is running in `unprivileged` mode, all other Elastic Agent commands need to be run without `sudo`. I've opened this PR to help make that warning more clear: https://github.com/elastic/ingest-docs/pull/1198

---
> (2) I would expect instructions / cli commands to switch an Elastic Agent
> If it is not possible, we should clearly state it (I think the workaround would be un-enrolling and re-installing? Do we lose the state?)

As far as I'm aware we don't have CLI commands to switch agent from `privileged` to `unprivileged`, nor the reverse. The workaround is, as you noted, to change the permissions of the user and group of Elastic Agent. I can try to make that more clear in the docs if you think that would help. I don't think re-enrolling the agent is required.

---
> (3) The section Agent and dashboard behaviors in unprivileged mode only mentions logs errors and missing info in the dashboards, but we do not tell anything about the Elastic Agent reported status in the Fleet UI. Will it be degraded? Unhealthy? Will the errors surface in the page below?

I don't think the "Agent details" page in Fleet shows anything about unprivileged agents being unhealthy, degraded, etc. Also, I don't think any error messages would appear there as a result of agent being in unprivileged mode.

However, a warning does show up on the Agent policies page if an unprivileged agent is enrolled in a policy that has integrations that require root privileges. That warning was added via https://github.com/elastic/kibana/pull/183946

---
> (4) Do we show the Elastic Agent is running as unprivileged in the Elastic Agent page?

As far as I know, only the Agent policies page shows the number of unprivileged agents, as documented [here](https://www.elastic.co/guide/en/fleet/8.15/elastic-agent-unprivileged.html#unprivileged-view-mode). 

---
> (5) Do we show the Elastic Agent is running as unprivileged in the Elastic Agent page?

From looking through the Kibana pull requests it doesn't seem so. However, the number of agents running in unprivileged mode is indicated on the Agent policies page, as documented [here](https://www.elastic.co/guide/en/fleet/8.15/elastic-agent-unprivileged.html#unprivileged-view-mode), and as added through [this code PR](https://github.com/elastic/kibana/pull/183077).

---

@ycombinator  Please keep me honest here. I'm happy to push whatever docs changes we might need (along with https://github.com/elastic/ingest-docs/pull/1198).

**Comment by lucabelluccini** [comment]
Thanks @kilfoyle 

For the **point (1)**, the Kibana Fleet UI suggests in the wizard to use `sudo ./elastic-agent install ...` and the `--unprivileged` info box doesn't mention to remove the `sudo`.
![image](https://github.com/user-attachments/assets/3a1584d9-0f30-4390-b416-b907b038d167)

The `sudo` is needed for `install`, but it's no more needed for the following commands.
The docs should say (suggestion):
> On Linux systems, once Elastic Agent is installed with `--unprivileged`, Elastic Agent commands ...

The "when you install [...] Elastic Agent commands should not run with `sudo`" are ambiguous (maybe it's just me).

For the **point (2)**, I've digged into the PRs and changes and it seems possible to switch via CLI via https://github.com/elastic/elastic-agent/pull/4621
So maybe we have to ask the engineers working on it.
The "only" limitation seems to be the fact we cannot switch via Fleet UI.

I have a suggestion (feel free to ignore it or use it if you think it might be valuable):
- Let's mention switching `privileged to unprivileged` requires to re-enroll and will trigger a state loss (duplicate ingestion & associated issues).
- Switching `unprivileged to privileged` is covered by your existing doc

If it turns out we have a CLI option, let's put it there too... I also wonder other edge cases such as switching an unprivileged to privileged via CLI... Would EA still use the user+group used or it would be completely ignored(?).

For the **point (3)** I've not tested 8.15, but https://github.com/elastic/beats/issues/39736 makes me think it will not be able to report unhealthy now, but it will in the future. Let's keep an eye on it.

For the **point (4)**, I do not have a 8.15 build handy, but in Serverless (which runs 8.16 Kibana Fleet) I see `Privilege mode` will be in 8.15 https://github.com/elastic/kibana/pull/183077:
<img width="701" alt="image" src="https://github.com/user-attachments/assets/ce8ef66f-1514-440a-bc0e-90fb10375cd8">

For the **point (5)**, I do not think we expose the info in the CLI looking at the code...

I've explicitly requested to have it in the diagnostics via https://github.com/elastic/elastic-agent/pull/4725 but it seems to only write to `agent-info.yml`, but it doesn't show up in the command line output

**Comment by ycombinator** [comment]
Thanks @kilfoyle.  As discussed in Slack, I'll let @blakerouse review #1200 as he's the SME on this topic.

**Comment by kilfoyle** [comment]
This should all be fixed by https://github.com/elastic/ingest-docs/pull/1200. Changes will show up in the docs soon.
Thanks for the suggestions @lucabelluccini
