### ISSUE TITLE
[REQUEST]: Document Fleet Remote ES output limitation with Traffic filters

### ISSUE THREAD

**Issue by juliaElastic** [elastic/ingest-docs#1206]
### Description

We need to document that using Remote ES output with a target cluster which has Traffic filters is not supported currently.
The main cluster's Fleet Server needs to have access to the remote cluster in order to create API keys, it would have to be enabled in traffic filters. Currently this is not supported, in ESS Fleet Server runs on an allocator, which doesn't have a publicly accessible IP address.

### Resources

https://www.elastic.co/guide/en/cloud/current/ec-restrictions.html#ec-restrictions-fleet-traffic-filters
https://www.elastic.co/guide/en/fleet/current/remote-elasticsearch-output.html

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @juliaElastic

**Stakeholders:** @fleet

**Comment by kilfoyle** [comment]
Thanks for opening this Julia! PR is here: https://github.com/elastic/ingest-docs/pull/1207
