### ISSUE TITLE
Docs for the Reusable Integration Policies feature in Fleet

### ISSUE THREAD

**Issue by kilfoyle** [elastic/ingest-docs#1220]
See:
 - Parent issue: https://github.com/elastic/ingest-dev/issues/1267
 - Walkthrough: https://github.com/elastic/kibana/issues/188707

Target: 8.16 (probably)
For 8.15 this is hidden behind a feature flag.

**Comment by omachala** [comment]
Hi! I can help update these screenshots.

I maintain [heroshot](https://heroshot.sh), a screenshot automation tool that captures screenshots from a config file using Playwright. Makes documentation maintenance easier since anyone can regenerate them when the UI changes.

Happy to submit a PR!
