### ISSUE TITLE
[REQUEST]: Document new task that automatically unenrolls inactive agents

### ISSUE THREAD

**Issue by criamico** [elastic/ingest-docs#1225]
### Description

There's a new feature coming in 8.16 that will allow the user to automatically unenroll inactive agents, based on a setting in agent policy. We need to have some docs about this new feature.

The setting in agent policy takes over the old unenroll timeout and reuses it for this new feature. 
![Screenshot 2024-08-06 at 12 31 37](https://github.com/user-attachments/assets/05500dd2-0ff3-42f3-9a28-e804447ce44c)

Inactive agents enrolled on policies with this setting enabled get unenrolled automatically. The task run every 10m and an unenroll a maximum of 1k agents at a time.

### Resources

Feature: https://github.com/elastic/kibana/issues/179399
PR: https://github.com/elastic/kibana/pull/189861

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @criamico

**Comment by kilfoyle** [comment]
Closed by https://github.com/elastic/ingest-docs/pull/1259
