### ISSUE TITLE
Formalize/document process for providing Fleet and Elastic Agent release notes

### ISSUE THREAD

**Issue by dedemorton** [elastic/ingest-docs#124]
We've been building the Fleet and Elastic Agent release notes by hand since version 7.13, but we need to formalize a process and start generating release notes.

02/15/2023 Edited to make this description more relevant.

**Comment by karenzone** [comment]
Related: https://github.com/elastic/elastic-agent-changelog-tool
Related work: https://github.com/elastic/elastic-agent/issues/2584
Thank you, @pierrehilbert.  

Is there an issue or meta-issue in the `elastic-agent` repo where we can identify next steps and track this work? 
Another option: We can relocate this issue to the `elastic`agent` repo for tracking. 

Goals: 
- Automated process with tooling to support
- Democratize the process to remove dependencies on a single person or subset of people. (Anyone on the team should be able to click the button after FF.) 
- When we've made this easy, make generating/merging release notes part of rotating Fleet/Agent Release Manager responsibilities. 

#### Next steps
- What would it take to get snippets output to asciidoc format in a DRAFT PR?

**Comment by karenzone** [comment]
Related: https://github.com/elastic/ingest-docs/issues/200

**Comment by pierrehilbert** [comment]
Hey Karen,
I'm out during next week but is it okay for you if we plan a meeting together when I will be back to be aligned on next steps and of what would make this changes a success from your point of view?

**Comment by karenzone** [comment]
Thank you, @pierrehilbert. I'm out the following week, but will set something up when I return.

**Comment by dedemorton** [comment]
Closing because this issue is quite old. If this work is still required, please open a new issue.
