### ISSUE TITLE
Update Documentation - TLS configuration of the Elastic Package Registry

### ISSUE THREAD

**Issue by kharsalan** [elastic/ingest-docs#1279]
Request to update [This doc](https://www.elastic.co/guide/en/fleet/current/air-gapped.html#air-gapped-tls) which includes information about TLS configuration of the Elastic Package Registry. However, we don't see anything specific about the TLS version settings.

`To force >= 1.2, Package Registry needs to be run with EPR_TLS_MIN_VERSION=1.2.`

**Comment by kpollich** [comment]
@kilfoyle - FYI I transferred this from `package-registry` to `ingest-docs`. @jsoriano can you confirm the above note about TLS versions is relevant + accurate and add anything else that we might need to get these docs updated?

**Comment by jsoriano** [comment]
We might say that Package Registry supports min TLS from 1.0 to 1.3, and defaults to 1.0.
In the next release the default will change to 1.2. It relies for defaults on the Go implementation https://pkg.go.dev/crypto/tls#Config.

**Comment by kilfoyle** [comment]
Thanks @jsoriano! I've opened https://github.com/elastic/ingest-docs/pull/1280 to add this to the docs.

> In the next release the default will change to 1.2.

Will this be for 8.16? If so, I'll open a separate PR for that.

**Comment by kilfoyle** [comment]
@kharsalan  Thanks for reporting this! The page you mentioned will be updated via https://github.com/elastic/ingest-docs/pull/1280
