### ISSUE TITLE
[REQUEST]: Add clarification on how/when metrics are collected

### ISSUE THREAD

**Issue by blakerouse** [elastic/ingest-docs#1303]
### Description

Customers are asking for more clarification on how and when metrics are collected for the system integration or the system metricbeat module. Specifically on when the metrics are collected and how the difference is computed between each metric collection interval.

Similar to this comment from the [KB](https://support.elastic.dev/knowledge/view/4c88b060):

> For example, the CPU usage in percent is calculated based on a time delta using the raw tick value (usually representing a millisecond) that indicates the total amount of CPU time a process has used. For example, if we collect the tick value for a process in 5 second intervals, and and the difference between the first tick value and the second is 1000 ticks, then we know the process has used 1 second of time in a 5 second interval, or 1/5, or 20%, of CPU time. In order to do this, we need three numbers: The first count of total cpu time, the second count, and the time between the counts. Hence why we need two values.

### Resources

This [KB](https://support.elastic.dev/knowledge/view/4c88b060) and this [SDH](https://github.com/elastic/sdh-beats/issues/5112) provides information on this request.

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @blakerouse 

**Stakeholders:** @tailorzed

**Comment by kilfoyle** [comment]
Here's a PR for the Beats docs: https://github.com/elastic/beats/pull/40715

The integrations docs are generated directly from the code so updating those would require an issue in the elastic/integrations repo. That being said, I think updating the Beats docs is all we need here.

**Comment by blakerouse** [comment]
@kilfoyle +1 from me

**Comment by kilfoyle** [comment]
Closed by https://github.com/elastic/beats/pull/40715
