### ISSUE TITLE
[REQUEST]: Document how to deploy Elastic Agent using Helm

### ISSUE THREAD

**Issue by ycombinator** [elastic/ingest-docs#1304]
### Description

In https://github.com/elastic/elastic-agent/pull/5331, @pkoutsovasilis added a [Helm](https://helm.sh/) chart for Elastic Agent.  We should add documentation showing users how to use this Helm chart to configure and deploy Elastic Agent on Kubernetes clusters, likely somewhere under https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html.

[UPDATE] Chatting with @cmacknz, we should mark the Elastic Agent Helm Chart as beta initially.

### Resources

* https://github.com/elastic/elastic-agent/pull/5331
* https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html
* https://helm.sh/

### Collaboration

The product team will provide the initial content.

### Point of contact.

**Main contact:** 
* @pkoutsovasilis – author of the PR that created the Helm Chart for Elastic Agent

**Stakeholders:**  
* @kilfoyle — technical writer for the Elastic Agent product portfolio
* @swiatekm — SME, along side @pkoutsovasilis, on Kubernetes

**Comment by nimarezainia** [comment]
@kilfoyle perhaps we should follow the layout here: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-stack-helm-chart.html, and place it under the installation section as mentioned. cheers

**Comment by pkoutsovasilis** [comment]
hi @ycombinator @nimarezainia 👋 sure writing a guidε on elastic site is a must-have. Howver, imo, there are three more "steps" that must happen before this issue can be completed:
1. Decide the release process of the Helm chart (more info [here](https://github.com/elastic/elastic-agent/pull/5331#discussion_r1739005237))
2. Wait for elastic-agent 8.16.0 to be released (and maybe we wanna target the Wolfi-based image as default)
3. Publish the first version of the Helm chart

That said, I do believe that this issue can start in parallel but certain bits and pieces depend on the above 🙂

**Comment by nimarezainia** [comment]
We intend to add this to the 8.16 list of features to publicize. Is there any chance of getting the docs in before 8.16? 
What is the issue with testing before 8.16 is publicly available? perhaps I can help.

**Comment by kilfoyle** [comment]
@nimarezainia I was thinking that testing might depend on the 8.16 elastic-agent image being available (Panos' second point in his [comment](https://github.com/elastic/ingest-docs/issues/1304#issuecomment-2337408470) above), but I can test with a snapshot version, so all good. I'll get this documented in time for 8.16 GA.

**Comment by kilfoyle** [comment]
Here's a PR for the docs, ready for review: https://github.com/elastic/ingest-docs/pull/1375

It includes a brief overview of the Helm chart and two walk-throughs, one for standalone agent and one for Fleet-managed. Whatever changes we need, let me know. :-)
