### ISSUE TITLE
[REQUEST]: Remove all mention of Beats namespace for Elastic Agent docker images

### ISSUE THREAD

**Issue by jlind23** [elastic/ingest-docs#1314]
### Description

Elastic Agent docker images are available under two different namespaces:
- `elastic-agent`
- `beats`

Our document almost always use the `beats` and we should update it to rather talk exclusively about the `elastic-agent` one.
Example: https://www.elastic.co/guide/en/fleet/current/elastic-agent-container.html

From 9.0 onwards, we plan to remove Elastic Agent images from the `beats` namespace.

This change can be performed in 8.15.x without issue.

### Resources

Example: https://www.elastic.co/guide/en/fleet/current/elastic-agent-container.html

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @jlind23 

**Stakeholders:** @ycombinator @cmacknz @pierrehilbert @nimarezainia

**Comment by kilfoyle** [comment]
Here are a couple of PRs to get the docs fixed up:
 - Fleet & Agent docs: https://github.com/elastic/ingest-docs/pull/1315
 - Observability docs: https://github.com/elastic/observability-docs/pull/4246
