### ISSUE TITLE
Make the ingest-docs repo public

### ISSUE THREAD

**Issue by dedemorton** [elastic/ingest-docs#15]
As described in [this meta issue](https://github.com/elastic/observability-docs/issues/2411), we want to make the ingest-docs repo public so that we can start moving source files and issues to the correct repo.

We need the repo to be public so that internal and external folks can:

* Click the Edit link in the docs to edit our source content.
* Open issues against the docs.

We do get quite a few contributions from developers and PMs who use the Edit link, so we need that to work before we move over the content.

**Comment by karenzone** [comment]
Done

**Comment by karenzone** [comment]
cc:/ @bmorelli25 Repo is ready to go. Thanks!

**Comment by ollyhowell** [comment]
Thanks @karenzone!
