### ISSUE TITLE
[REQUEST]: Increase agent policy count recommendation to 1000 for stateful deployments

### ISSUE THREAD

**Issue by kpollich** [elastic/ingest-docs#1551]
### Description

We've evaluated and tested Fleet/Kibana and have made a few changes that allow us to support more agent policies in Fleet's various UIs and API endpoints. With this in mind, we'd like to increase this recommendation from 500 policies to 1000 policies: https://www.elastic.co/guide/en/fleet/current/fleet-server-scalability.html#:~:text=A%20single%20instance%20of%20Fleet,UI%20performance%20might%20be%20impacted.. 

However, due to the resource constraints on our managed Fleet Server in Elastic Serverless, we can't make the same recommendation for serverless projects. We should note that for serverless projects we recommend a maximum policy count of 500. 

### Resources

https://www.elastic.co/guide/en/fleet/current/fleet-server-scalability.html#:~:text=A%20single%20instance%20of%20Fleet,UI%20performance%20might%20be%20impacted.

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @kpollich

**Stakeholders:** @kpollich

**Comment by amitkanfer** [comment]
So we're suggesting to make the distinction between stateful and serverless in the docs?

**Comment by kpollich** [comment]
@amitkanfer - Correct. Not sure if we've done this before elsewhere, but the resource limits in serverless necessitate the lower recommendation.

**Comment by kilfoyle** [comment]
Here's a docs PR: https://github.com/elastic/ingest-docs/pull/1563

**Comment by jlind23** [comment]
@kpollich @nchaulet @kilfoyle according to a recent discussion we had within Ingest, it seems that we could also update this to reflect the number of policies per space that we do support + the number of policies instead of just the number of policies.

**Comment by nchaulet** [comment]
> @kpollich @nchaulet @kilfoyle according to a recent discussion we had within Ingest, it seems that we could also update this to reflect the number of policies per space that we do support + the number of policies instead of just the number of policies.

Not sure to totally understand here, number of policies per space we support is the same as the number of policies we support

**Comment by jlind23** [comment]
Test added by David is:
`A single instance of {fleet} supports a maximum of 1000 {agent} policies. If more policies are configured, UI performance might be impacted.`

Shall we add something like this?
`A single instance of {fleet} supports a maximum of 1000 {agent} policies. If more policies are configured, UI performance might be impacted. This maximum number of policies is not affected by any mean by the number of space these policies are scattered across.`

**Comment by kilfoyle** [comment]
`A single instance of {fleet} supports a maximum of 1000 {agent} policies. If more policies are configured, UI performance might be impacted. The maximum number of policies is not affected by the number of spaces in which the policies are used.`

How about the above?  Just a slight rewording to Julien's suggestion.

**Comment by kilfoyle** [comment]
[PR](https://github.com/elastic/ingest-docs/pull/1563) is updated with the spaces text.
