### ISSUE TITLE
[Fleet]: Need to remove Subcategories feature from Release notes.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#162]
**Description:**
As per update under https://github.com/elastic/kibana/issues/147125 , the "Implement subcategories in integrations UI" feature is moved to 8.8, so it is required to be removed from the 8.7 Release notes.

**Link:**
https://www.elastic.co/guide/en/fleet/8.7/release-notes-8.7.0.html#new-features-8.7.0

**Screenshot:**
![image](https://user-images.githubusercontent.com/77374876/233102601-bed0a207-9e09-4572-9d68-98d811ccfb4c.png)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
FYI @kpollich

**Comment by kilfoyle** [comment]
Sure, I'll look after this today.
