### ISSUE TITLE
Add steps to generate Elastic Agent diagnostic from Fleet in the troubleshooting page

### ISSUE THREAD

**Issue by naj-h** [elastic/ingest-docs#165]
Can we add the steps to generate a diagnostic from Fleet UI for Fleet-managed agents in the troubleshooting doc?

Add these steps: https://www.elastic.co/guide/en/fleet/master/monitor-elastic-agent.html#collect-agent-diagnostics

In the following doc section: https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html#_collect_elastic_agent_diagnostics_bundle

The reason is that the steps to do so from the Fleet UI might be easier and quicker for customers, and in some scenarios the customers don't have SSH access to the endpoints where Elastic agent is installed, so running the diagnostics from Fleet might be their only option. The troubleshooting page should contain a reference to how to execute the diagnostic from Fleet.

**Comment by kilfoyle** [comment]
@naj-h I'm sorry this issue took so long to get to. I've updated the [Collect Elastic Agent diagnostics bundle](https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html#_collect_elastic_agent_diagnostics_bundle) section of the Troubleshooting docs so it now includes instructions for both collection through the CLI command, and through the Fleet UI. Please let me know if anything doesn't look right.
