### ISSUE TITLE
Add port numbers to diagrams in the Ingest Architecture docs

### ISSUE THREAD

**Issue by nimarezainia** [elastic/ingest-docs#197]
We have the ports defined in this table: https://www.elastic.co/guide/en/fleet/current/add-fleet-server-on-prem.html#default-port-assignments-on-prem, however generally difficult to find.

It would be great if these ports are on the actual pictures we have for the ingest architectures so that the user can quickly determine ports they need to open. THis was a request from a user who was frustrated with docs. I think it's a good idea.

**Comment by karenzone** [comment]
#### Tracking

- [ ] Elastic Agent to Elasticsearch: Agent installed
- [ ] Elastic Agent to Elasticsearch: APIs for collection

- [ ] Elastic Agent to Logstash for enrichment
- [ ] Elastic Agent to Logstash for buffering
- [ ] Elastic Agent to Logstash as a proxy
- [ ] Elastic Agent to Logstash to multiple destinations

- [ ] Elastic Agent to proxy to Elasticsearch

- [ ] Elastic Agent with Kafka middleware (ES Sink)
- [ ] Elastic Agent with Kafka middleware (Logstash)

- [ ] Logstash to Elasticsearch

**Comment by karenzone** [comment]
@nimarezainia  First round of architectures with port numbers added is ready for review:

- [ ] Elastic Agent to Elasticsearch: Agent installed (WIP #375)
- [ ] Elastic Agent to Elasticsearch: APIs for collection (WIP #375)

**Comment by karenzone** [comment]
@nimarezainia Next round of architectures with port numbers added is ready for review in PR #394:

- Elastic Agent to Logstash for enrichment 
- Elastic Agent to Logstash for buffering 
- Elastic Agent to Logstash as a proxy
- Elastic Agent to Logstash to multiple destinations 
- Elastic Agent to proxy to Elasticsearch 
- Elastic Agent to proxy to Elasticsearch (Self-managed Fleet Server) 
- Elastic Agent with Kafka middleware (ES Sink) 
- Elastic Agent with Kafka middleware (Logstash)

**Comment by karenzone** [comment]
Closed with merge of these PRs:
* #375 
* #394
