### ISSUE TITLE
[Fleet] Document our per-integration health reporting

### ISSUE THREAD

**Issue by jlind23** [elastic/ingest-docs#209]
Agent details UI will soon be enhanced and it will allow users to quickly access lgos and failures that might impact a given agent.

This new menu and options should be documented.

Related Kibana issue: https://github.com/elastic/kibana/issues/154634
Related PR: https://github.com/elastic/kibana/pull/158826

**Comment by jlind23** [comment]
@karenzone @kilfoyle could you please help me assign the right label to this?

**Comment by karenzone** [comment]
Dev work inflight:  https://github.com/elastic/kibana/pull/158826

**Comment by karenzone** [comment]
@kilfoyle This one. @jillguyonnet will be doing a demo later this week, and recording it for us.
