### ISSUE TITLE
Implement backport automation for `ingest-docs` repo

### ISSUE THREAD

**Issue by karenzone** [elastic/ingest-docs#210]
Evaluate and implement best approach:
* Label-based backports (example: [`observability docs`](https://github.com/elastic/observability-docs) repo
   Quicker and easier way to get backport PRs created.
   Ease (just add a label) encourages backporting to outdated branches without any deliberation
* Comment-based backports (example: [`logstash`](https://github.com/elasticlogstash) repo
   Easy to trigger with a saved GitHub response, but not quite as easy as label-based backport. Requires a bit more deliberation. 

Note:  I'm opening this issue in `ingest-docs` for now, but we will likely need some level of assistance from dev

**Comment by jrodewig** [comment]
Unless there are objections, I can work on setting up automated label-based backports using mergify (the same way Observability docs and Stack docs do).

I've not done it before, but we should be able to accomplish it without developer support:

- [ ] Submit an SRE request to add ingest-docs to mergify (https://elasticco.atlassian.net/browse/SRE-364 -- sorry, internal only link)
- [ ] Add mergify configuration and labels to the repo
