### ISSUE TITLE
[Fleet]: Unenrolled status is not available under mentioned view agent status screenshot

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/ingest-docs#232]
**Description:**
Unenrolled status is not available under mentioned view agent status screenshot

**Link:**
- https://www.elastic.co/guide/en/fleet/current/monitor-elastic-agent.html

**Screen-shot:**

![image_720](https://github.com/elastic/ingest-docs/assets/101545338/e9755c19-c0ed-4189-9e4c-e246be9a452c)

**Comment by kilfoyle** [comment]
Sorry, re-opening this as I closed the wrong issue by mistake (I meant to close #/232 in the platform-docs-team repo instead). I'll fix this one asap.

**Comment by harshitgupta-qasource** [comment]
Hi @kilfoyle

Thank you for the fixes.
We have revalidated the latest docs and found this issue **fixed now**.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/monitor-elastic-agent.html


**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/101545338/8a4296b8-a8b2-4a40-9ef5-341e3508d8e7)

Hence we are marking this issue as **QA:Validated**.

Thanks
