### ISSUE TITLE
[Fleet]: Example Fleet Server commands are missing `--fleet-server-port=8220`.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#233]
**Description:**
Example Fleet Server commands are missing `--fleet-server-port=8220`.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html#_examples_10
- https://www.elastic.co/guide/en/fleet/current/secure-connections.html#_encrypt_traffic_between_elastic_agents_fleet_server_and_elasticsearch

**Screenshots:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/883e486f-2180-4cb7-bc40-4e6c61ee0b06)
![image](https://github.com/elastic/ingest-docs/assets/77374876/336b32bc-884a-4a8a-8a46-fd9c83af60a2)
![image](https://github.com/elastic/ingest-docs/assets/77374876/c8f1e8a0-fef7-405f-91b1-7d6f5049ff0b)

**Expected:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/d5b07b24-ed11-4516-8e29-70072e55103e)
![image](https://github.com/elastic/ingest-docs/assets/77374876/648cd3ce-f213-4cc1-a2aa-36dd42673840)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amitkanfer** [comment]
@karenzone

**Comment by kilfoyle** [comment]
The docs will be updated with the next build. Sorry that this took so long to get to!

**Comment by amolnater-qasource** [comment]
Hi @kilfoyle 

We have revalidated the latest docs and found this issue **fixed now**.

**Links:**
- https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html#_examples_10
- https://www.elastic.co/guide/en/fleet/current/secure-connections.html#_encrypt_traffic_between_elastic_agents_fleet_server_and_elasticsearch

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/dd64fcbb-cb2b-49ff-b860-78e3258c8554)

Hence we are marking this issue as **QA:Validated**.

Thanks
