### ISSUE TITLE
[Fleet]: Agents tab screenshots are missing Agent Info Metrics links and Ingest Overview Metrics links.

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/ingest-docs#234]
**Description:**
Agents tab screenshots are missing Agent Info Metrics and Ingest Overview Metrics links.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/migrate-beats-to-agent.html
- https://www.elastic.co/guide/en/fleet/current/install-fleet-managed-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/current/elastic-agent-container.html
- https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-managed-by-fleet.html
- https://www.elastic.co/guide/en/fleet/8.8/monitor-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/current/upgrade-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/current/agent-policy.html
- https://www.elastic.co/guide/en/fleet/current/filter-agent-list-by-tags.html

**Screen Shot:**
![image](https://github.com/elastic/ingest-docs/assets/101545338/713f742b-fb40-4c7c-94d8-d054fbeb6c41)

**Expected Result**
![image](https://github.com/elastic/ingest-docs/assets/101545338/03453b15-72cc-40ce-86fa-8e3f2db98ba4)

**Comment by amolnater-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amitkanfer** [comment]
@karenzone

**Comment by kilfoyle** [comment]
Thanks a lot for opening this @harshitgupta-qasource!
I've gone through the links and all of the screen captures are updated now. The last one in the list will be fixed by https://github.com/elastic/ingest-docs/pull/616

Note that [this link](https://www.elastic.co/guide/en/fleet/8.8/monitor-elastic-agent.html) is not fixed, but the [equivalent page](https://www.elastic.co/guide/en/fleet/current/monitor-elastic-agent.html) in v8.10 and higher has been fixed.

**Comment by harshitgupta-qasource** [comment]
Hi @kilfoyle

We have revalidated the latest docs and found this issue **fixed now**.

**Links:**
- https://www.elastic.co/guide/en/fleet/current/migrate-beats-to-agent.html
- https://www.elastic.co/guide/en/fleet/current/install-fleet-managed-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/current/elastic-agent-container.html
- https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-managed-by-fleet.html
- https://www.elastic.co/guide/en/fleet/8.8/monitor-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/current/upgrade-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/current/agent-policy.html
- https://www.elastic.co/guide/en/fleet/current/filter-agent-list-by-tags.html

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/101545338/ef6255a9-120f-4f71-859a-df2ffb0d8880)

Hence we are marking this issue as **QA:Validated**.

Thanks
