### ISSUE TITLE
[Fleet]: --basepath info missing under elastic docs for 8.8.0.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#237]
**Description:**
--basepath info is missing under elastic docs for 8.8.0.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/installation-layout.html

**Implemented under PR:** 
https://github.com/elastic/ingest-docs/pull/160

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/2735a01f-53fa-4603-b25a-34bbf1247b0d)

**Comment by ycombinator** [comment]
This is as intended.  We have not releases the `elastic-agent --base-path` feature yet.  We initially merged that feature but then it was rolled back.  So there is no documentation for it either.  Related: https://github.com/elastic/elastic-agent/pull/2592 and https://github.com/elastic/ingest-docs/pull/189.

Once https://github.com/elastic/elastic-agent/issues/2599 is implemented, the feature can be re-released along with documentation.

**Comment by amolnater-qasource** [comment]
Hi @ycombinator 

Thank you for the update, we weren't aware about this change.
As the feature is not released in 8.8.0, we are closing this issue.

Further we will revalidate the docs once the feature is released.

Thanks!
