### ISSUE TITLE
[Fleet]: Subcategories filters in integrations UI details missing under elastic docs for 8.8.0. 

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/ingest-docs#238]
**Description:**
Subcategories filter in integrations UI details missing under elastic docs for 8.8.0. 

**Link:**
- https://www.elastic.co/guide/en/fleet/current/integrations.html

**Implemented under Feature Ticket:** 
https://github.com/elastic/kibana/issues/147125

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/101545338/a599734a-11fc-4415-91eb-2d0c3b21f500)

**Comment by harshitgupta-qasource** [comment]
@amolnater-qasource Kindly review

**Comment by amolnater-qasource** [comment]
Secondary review for this ticket is Done

**Comment by kilfoyle** [comment]
In https://github.com/elastic/ingest-docs/pull/632 I've added a note to several pages about the integrations docs indicating that users can filter the list of integrations by selecting a category from the list.

**Comment by harshitgupta-qasource** [comment]
Hi @kilfoyle

We have revalidated the latest docs and found this issue **fixed now**.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/add-integration-to-policy.html
- https://www.elastic.co/guide/en/fleet/current/view-integration-policies.html
- https://www.elastic.co/guide/en/fleet/current/install-uninstall-integration-assets.html
-


**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/101545338/cc5e0670-ee96-4d33-afc5-c0fc5eb69bb8)

Hence we are marking this issue as **QA:Validated**.

Thanks
