### ISSUE TITLE
We should document this behaviour in our public doc page for standalone agent

### ISSUE THREAD

**Issue by jlind23** [elastic/ingest-docs#240]
We should publicly document that Elastic Agent file paths can not exceed 103 or else the path will be rewrite to something like:
`/tmp/elastic_agent/$sha256(path).sock` instead of `unix:///usr/share/elastic-agent/state/data/tmp/kubernetes-metrics-60f88f50-c873-11ed-9baf-09fb5640c56a.sock` where $sha256(path) is the SHA256 hash of the original path that is too long.

**Comment by jlind23** [comment]
@kilfoyle @karenzone This should be fairly small to document, would it be feasible to add it to our 8.8 docs as soon as possible?

**Comment by kilfoyle** [comment]
@jlind23  I'll add it in today.
