### ISSUE TITLE
Claim in docs that we don't support PowerShell ISE then with the elastic-agent command

### ISSUE THREAD

**Issue by jlind23** [elastic/ingest-docs#267]
### Description

While performing some tests, we discovered that elastic-agent command do not work under PowerShell ISE. PowerShell has been put in a maintenance mode so we should basically claim that we do not support it instead of fixing the issue.

### Resources

https://github.com/elastic/elastic-agent/issues/2902

### Collaboration

The product team will provide the initial content.

### Point of contact.

**Main contact:** @jlind23 

**Stakeholders:** @nimarezainia

**Comment by cmacknz** [comment]
See also https://github.com/elastic/ingest-docs/issues/264, which I'll close as a duplicate.

**Comment by yaparlareddy** [comment]
@cmacknz @jlind23  any updated on this issue and when it will be fixed?

**Comment by kilfoyle** [comment]
Thanks for the reminder @yaparlareddy. I'll try to fit this in next week.
