### ISSUE TITLE
IngestArch: "Napkin sketches" for air-gapped architecture and data safety (buffering at the edge)

### ISSUE THREAD

**Issue by karenzone** [elastic/ingest-docs#272]
Create conceptualized view of air-gapped architecture (or architectures). The graphic should be similar in concept and style to existing architecture diagrams in [Elasticsearch Ingest Architectures](https://www.elastic.co/guide/en/ingest/current/use-case-arch.html). 

#### How we make progress
@nimarezainia For existing architecture diagrams, we started with an internal slide deck (which I can share) with a wide range of architectures. We picked a relevant diagram to use as a baseline, and then identified modifications we wanted.  I made initial drawings in Figma, and then we iterated. 

I'm flexible and open to whatever approach works best for you.

**Comment by karenzone** [comment]
First working session scheduled for 2023-0718, Tu.

**Comment by karenzone** [comment]
@nimarezainia: Need an update for planning, please.  What is your target date(s) for providing: 
- [ ] List of architectures to be reproduced as air-gapped (ideally in order of priority)
- [ ] "Napkin sketches" for first one-three architectures so that I can start drawing. (As we discussed, we can work together to come up with rough diagrams over zoom. If async is easier for you considering the timezome diff, you can rough out sketches electronically, or even draw on paper and send me a scan.  Whatever works best for you.

**Comment by nimarezainia** [comment]
@karenzone sorry for the delay.

the two architectures are:
1) [Elastic Agent to Elasticsearch](https://www.elastic.co/guide/en/ingest/current/agent-installed.html)
2) [Elastic Agent to Logstash](https://www.elastic.co/guide/en/ingest/current/ls-enrich.html)

I'll get the drawing to you asap

**Comment by nimarezainia** [comment]
For #1 : 
<img width="1019" alt="image" src="https://github.com/elastic/ingest-docs/assets/13442829/6f667cea-3f0c-4585-8b84-fd860c586fd0">

**Comment by nimarezainia** [comment]
for (2):

<img width="1071" alt="image" src="https://github.com/elastic/ingest-docs/assets/13442829/9c00ef1f-003b-493a-a607-c4e5dad566e0">

**Comment by karenzone** [comment]
Thank you, @nimarezainia! This gets us off to a good start.  
Please keep going while I make use of this info you've provided.

**Comment by karenzone** [comment]
Related issues to turn around first two sketches:

- [ ] #370 
- [ ] #371

**Comment by karenzone** [comment]
Napkin sketches are done.  Issues for creating diagrams:

* #370 
* #371
