### ISSUE TITLE
Agent detail page UI not matching in documentation

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/ingest-docs#286]
**Description**
Agent detail page UI not matching in documentation

**URL link**

- https://www.elastic.co/guide/en/fleet/8.6/migrate-beats-to-agent.html

**Screen-Shot**

- Actual result

![image](https://user-images.githubusercontent.com/59917825/211753849-bbc55081-4847-4b7e-9150-b53accf51fba.png)

- Expected result

![image](https://user-images.githubusercontent.com/59917825/211753796-8f0ca111-d394-4b05-a81f-1cebfd896925.png)

**Comment by kilfoyle** [comment]
Thanks very much for reporting this @karanbirsingh-qasource! The pages will be updated soon, via https://github.com/elastic/ingest-docs/pull/548

**Comment by amolnater-qasource** [comment]
Hi @kilfoyle 

Thank you for the fixes. 
We have revalidated the latest docs and found this issue **fixed now**.

**Links:**
- https://www.elastic.co/guide/en/fleet/8.11/migrate-beats-to-agent.html

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/fbed848b-e529-4b84-a733-3a78f5d4729c)

Hence we are marking this issue as **QA:Validated**.

Thanks
