### ISSUE TITLE
Standalone Elastic agent requires root permission to be installed

### ISSUE THREAD

**Issue by jasonyoum** [elastic/ingest-docs#29]
Hello!

Elastic agent [Capabilities comparison](https://www.elastic.co/guide/en/fleet/8.1/beats-agent-comparison.html#additional-capabilities-beats-and-agent) document page describes Standalone Elastic agent can "run without root on host" but [Install standalone Elastic Agents (advanced users)](https://www.elastic.co/guide/en/fleet/8.1/install-standalone-elastic-agent.html#install-standalone-elastic-agent) page describes "You must run this command ($ sudo ./elastic-agent install) as the root user because some integrations require root privileges to collect sensitive data". It sounds like one of above pages need to be corrected. 

Can you please check and correct them to avoid any confusions there?

Thank you!

**Comment by nimarezainia** [comment]
https://github.com/elastic/observability-docs/pull/2463
