### ISSUE TITLE
Agent Activity and Add Fleet Server missing under doc of fleet

### ISSUE THREAD

**Issue by karanbirsingh-qasource** [elastic/ingest-docs#294]
**Description**
Agent Activity and Add Fleet Server missing under doc of fleet

**URL link**

- https://www.elastic.co/guide/en/fleet/8.6/fleet-overview.html
- https://www.elastic.co/guide/en/fleet/8.6/migrate-beats-to-agent.html
- https://www.elastic.co/guide/en/fleet/8.6/install-fleet-managed-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/8.6/monitor-elastic-agent.html

**Screen-Shot**

- Actual result

![image](https://user-images.githubusercontent.com/59917825/211753071-15aa4198-37d7-44f0-a072-86f151b54038.png)

- Expected result

![image](https://user-images.githubusercontent.com/59917825/211753028-4e4a7ee3-54f3-4916-b4f6-9171b6412a73.png)

**Comment by amolnater-qasource** [comment]
Hi @kilfoyle 

We have revalidated the latest docs and found this issue **fixed now**.

**Links:**

- https://www.elastic.co/guide/en/fleet/8.11/fleet-overview.html
- https://www.elastic.co/guide/en/fleet/8.11/migrate-beats-to-agent.html
- https://www.elastic.co/guide/en/fleet/8.11/install-fleet-managed-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/8.11/monitor-elastic-agent.html

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/88f3b888-0e9d-4880-85dd-86199986d70b)


Hence we are marking this issue as **QA:Validated**.

Thanks
