### ISSUE TITLE
[Request] Document that Fleet agent list pagination is limited to 500 pages (10000 agents)

### ISSUE THREAD

**Issue by juliaElastic** [elastic/ingest-docs#296]
## Description

Related to https://github.com/elastic/kibana/issues/91562#issuecomment-1157866528

In 8.4 we decided to limit the display of Fleet Agent list to 10000 items due to technical limitations. This means 500 pages with page size 20.
We should document this fact to avoid confusion and encourage users to use filtering and sorting to narrow down the agent list to less than 10k records.

## Collaboration

- The docs team will lead producing the content

**Contact Person:** @juliaElastic 

## Suggested Target Release

preferably 8.6

## Stakeholders

@elastic/fleet

**Comment by lucabelluccini** [comment]
++ Users are hitting this limitation. It's very important to document this, but in parallel we should open a tracking issue to enhance the experience with a scroll/pit context to allow navigating 10k+ agents
