### ISSUE TITLE
[REQUEST]: Include capabilities in integrations documentation

### ISSUE THREAD

**Issue by jsoriano** [elastic/ingest-docs#307]
### Description

With the arrival of serverless, we are going to have different offerings with different feature sets. We have packages that depend on some of the features that may not be always available. These packages won't be exposed to users of these offerings.
It would be nice to include in the public integrations documentation some reference to the offerings where each integration is going to be available.

This will probably imply to update the scripts used to generate integrations documentation.

### Resources

* Proposal document for [Packages availability on different Stack offerings](https://docs.google.com/document/d/1npWqlfKDoCaJh290TfggclWOUYOCfS2ksinkVcMKY2k/edit)
* The different features are enabled or disabled depending on the Kibana configuration (available [here](https://github.com/elastic/kibana/tree/a4889b48517ea79974a2eca584f0c7273a6f032a/config)).
* Packages will include the set of capabilities they support (see https://github.com/elastic/package-spec/issues/560).
* We will need to implement some similar tooling in elastic-package to help package developers know on what offerings their packages are going to be available (see https://github.com/elastic/elastic-package/issues/1343).
* Part of https://github.com/elastic/ingest-dev/issues/2186.

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @jsoriano 

**Stakeholders:** @elastic/fleet

**Comment by jlind23** [comment]
@kilfoyle timing wise our development our development will probably be done by end of July and included in our next minor release (8.10).

**Comment by bmorelli25** [comment]
Just to make sure I'm understanding correctly.

By the end of July, all integrations will include a `conditions.elastic.capabilities` array?
Example from https://github.com/elastic/package-spec/issues/560:

```
conditions:
  kibana.version: '^8.10.0'
  elastic.subscription: 'basic'
  elastic.capabilities:
    - apm
    - uptime 
 ```

The ask for the docs team: read and publish these capabilities as a part of our daily doc build. Obviously, we could work on the text and implementation, but a very basic example might look like this?

<img width="986" alt="Screenshot 2023-07-06 at 12 07 11 PM" src="https://github.com/elastic/ingest-docs/assets/5618806/500efb66-f28c-4411-adac-49d7bead043c">

**Comment by jsoriano** [comment]
> all integrations will include a `conditions.elastic.capabilities` array?

Not all integrations. Only packages that require any of these capabilities will have these conditions. Consider this as something that can be optionally in a package.

The packages with these conditions won't be available in deployments without these plugins or features. For example Serverless Security deployments won't have the APM plugin, so the APM package won't be available there.

From the documentation side, we could leverage this to indicate on what offerings the package is going to be available.

More than showing them as capabilities of a package, we should show this capabilities as requirements, and/or we should show on what offerings the package is available.

**Comment by bmorelli25** [comment]
Thanks, @jsoriano!

@jlind23 I'm moving this from Platform to Observability docs. Please let us know if the timeline expressed in https://github.com/elastic/ingest-docs/issues/307#issuecomment-1621202167 changes.

**Comment by bmorelli25** [comment]
Is this change still being planned for 8.10?

**Comment by jlind23** [comment]
@bmorelli25 That is correct. @jsoriano and @mrodm delivered it in 8.10

**Comment by bmorelli25** [comment]
Do you have an example of a package that includes the new `elastic.capabilities` variable? I searched the integrations repo, and I can't find any.

**Comment by bmorelli25** [comment]
I'm still struggling to see this change anywhere. Can someone help me understand what I'm looking for so we can implement this?

**Comment by jlind23** [comment]
hey @bmorelli25 sorry for the late reply here, here are some information:
- This [PR](https://github.com/elastic/package-spec/pull/561/files#diff-64d59dfc19d2aa9fce86ddbe193f27ba9f72cd44adee4be6e92a67f4330f2f09) contains an example of a manifest that contains a capability.
- Capabilities definition can be found [here](https://github.com/elastic/package-spec/blob/889754b93f7ee6f48651630dc4315cc59d43ec3b/spec/integration/manifest.spec.yml#L104-L119)

**Comment by colleenmcginnis** [comment]
Done in https://github.com/elastic/integration-docs/pull/222 🎉

**Comment by jsoriano** [comment]
Looks great, thanks!
