### ISSUE TITLE
[Fleet] Fleet API documentation update

### ISSUE THREAD

**Issue by jillguyonnet** [elastic/ingest-docs#315]
We are introducing some changes to Fleet API for [Package Policies](https://www.elastic.co/guide/en/fleet/master/fleet-apis.html#PackagePolicies) endpoints that should be reflected in the documentation.

In this change, the following endpoints have a new `format` query parameter that defines how the package inputs are formatted:

- [GET /package_policies](https://www.elastic.co/guide/en/fleet/master/fleet-apis.html#getPackagePolicies)
- [GET /package_policies/{packagePolicyId}](https://www.elastic.co/guide/en/fleet/master/fleet-apis.html#getPackagePolicy)
- [POST /package_policies](https://www.elastic.co/guide/en/fleet/master/fleet-apis.html#createPackagePolicy)
- [POST /package_policies/_bulk_get](https://www.elastic.co/guide/en/fleet/master/fleet-apis.html#bulkGetPackagePolicies)
- [PUT /package_policies/{packagePolicyId}](https://www.elastic.co/guide/en/fleet/master/fleet-apis.html#updatePackagePolicy)

The `format` query parameter can take two values:
- `legacy` (default, same as not passing the parameter): inputs are formatted as an array
- `simplified`: inputs are formatted as a map

Note that the simplified map format is the new recommended format for package inputs. This is already reflected in the documentation for creating a package policy in the [package policy request schema](https://www.elastic.co/guide/en/fleet/master/fleet-apis.html#package_policy_request). While the legacy array format is still accepted, it is not explicitly documented there.

Finally, note that the following query parameters have also been made explicit for the [GET /package_policies](https://www.elastic.co/guide/en/fleet/master/fleet-apis.html#getPackagePolicies) endpoints:
- `perPage`
- `page`
- `kuery`

This should also be reflected in the documentation, similarly to the [GET /agent_policies](https://www.elastic.co/guide/en/fleet/master/fleet-apis.html#agentPolicyList) endpoint.

Relate Kibana issue: https://github.com/elastic/kibana/issues/155044
Related Kibana PR: https://github.com/elastic/kibana/pull/160921

**Comment by jillguyonnet** [comment]
@kilfoyle Can you let me know if the tags and description look correct for this issue? I'm also available for any questions or clarification.

**Comment by kilfoyle** [comment]
@jillguyonnet Thanks for opening this! The Fleet API docs are generated from this [Open API spec file](https://github.com/elastic/kibana/blob/main/x-pack/plugins/fleet/common/openapi/bundled.json) following the steps in [this readme file](https://github.com/elastic/ingest-docs/tree/main/docs/en/ingest-management/fleet/api-generated#readme).

Do you happen to know if that spec file is already up-to-date to include the Package Policies endpoints? If so, I can certainly re-generate the docs.

(By the way, I noticed a small error in my readme instructions and that will be fixed once I merge [this small PR](https://github.com/elastic/ingest-docs/pull/316).)

**Comment by kilfoyle** [comment]
I forgot to mention, the tags and description look perfect. 👍

**Comment by jillguyonnet** [comment]
Thank you @kilfoyle for the link, that's awesome. I merged the PR this morning, so the Open API spec file is now up-to-date. 🙂 Let me know if you need anything else from our end.

**Comment by kilfoyle** [comment]
Here's a PR to update the generated API docs: https://github.com/elastic/ingest-docs/pull/322
