### ISSUE TITLE
[REQUEST]: Document current behavior of asset installation on multiple spaces

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/ingest-docs#324]
### Description

Elastic Agent Integration assets can be installed only on a single space.

Elastic Agent Integration assets are composed of different kind of assets:
- some assets are Elasticsearch assets and cannot be space aware
- some assets are Kibana spaces aware

Users might be confused by the fact installing one integration in one space prevents the installation of the same integration on another space.
We should guide the users to tell what to do in case they want to have the same assets (e.g. dashboards) on another space.

If a user visits the page of an integration which is already installed, they get `This integration is installed, but no assets are available in this space`. We might improve this with a pointer to a documentation to tell what to do if a user wants the dashboards on another space.

The generic answer would be to `Copy to Spaces` functionality, but I am not 100% sure this is the long term solution.

We should also notify it's not possible to have multiple versions of the same integration running.
As soon we upgrade an integration, the "old" assets get removed, invalidating the possibility to have multiple integrations running. Also Index Templates do not have a "discriminant" on the integration version.

### Resources

Current page only shows https://www.elastic.co/guide/en/fleet/8.8/install-uninstall-integration-assets.html

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** I think the main contacts should be @kpollich @hop-dev but I am not 100% sure.

**Comment by kilfoyle** [comment]
Hi @lucabelluccini and @yomduf, I opened a PR to add notes to the docs, as suggested. Please let me know what changes you'd like.  https://github.com/elastic/ingest-docs/pull/504

**Comment by kpollich** [comment]
Added docs link in https://github.com/elastic/kibana/pull/168097
