### ISSUE TITLE
[Serverless] Create placeholders for ingest pages based on ES3 docs plan

### ISSUE THREAD

**Issue by kilfoyle** [elastic/ingest-docs#389]
Migrate pages from Sandbox to Staging for the Ingest topics described in the [ES3 docs plan](https://docs.google.com/spreadsheets/d/1jk-KmKeJbMYPw-pGA1lfzyHrBiDDK-msJLDNa94SBKg/edit#gid=0).

**Comment by karenzone** [comment]
Placeholders and more added with merge of https://github.com/elastic/staging-serverless-elasticsearch-docs/pull/48
