### ISSUE TITLE
[REQUEST]: Make clear that self-managed Fleet Server is not supported on Serverless

### ISSUE THREAD

**Issue by joshdover** [elastic/ingest-docs#413]
### Description

Serverless projects will not support deploying a Fleet Server on-premise and we need to make this clear in the documentation. The UI for this is not available in the product.

### Resources

This entire "Set up Fleet Server" section and sub-pages is not supported on Serverless: https://www.elastic.co/guide/en/fleet/current/fleet-server.html

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @jsoriano 

**Stakeholders:**
- @joshdover 
- @nimarezainia

**Comment by nimarezainia** [comment]
Generic question about modifications for the purposes of serverless: What version of our docs should these type of changes go into?

**Comment by joshdover** [comment]
@kilfoyle can answer more but I think the idea is that we actually have separate docs for serverless. So this may be more of a subtraction exercise when porting the docs over?

**Comment by kilfoyle** [comment]
Great questions, and honestly I'm still getting clear about the Serverless plans myself. For now, I'm keeping track of the Serverless docs requirements, but I think some will need to wait until we're ready to migrate the docs over.

For Serverless MVP in late October we'll likely have just a few ingest pages that point into the current docs. I'm discussing with the team how we'll mark restrictions in the current docs about what's not supported on Serverless. The eventual plan, though, is to have a copy of the Fleet & Agent guide in the separate Serverless docs site. In making that copy, exactly as you suggest @joshdover, we can subtract any features that don't apply in Serverless, including on-prem Fleet Server.

Somewhat related: Am I correct to understand that the Fleet UI will be available in Serverless Observability and Security projects, but not Elasticsearch projects? At least, that's what I see in the UI currently.

**Comment by joshdover** [comment]
> Am I correct to understand that the Fleet UI will be available in Serverless Observability and Security projects, but not Elasticsearch projects? At least, that's what I see in the UI currently.

Yes that is correct. Fleet will not be available on Elasticsearch/ES3 projects.

**Comment by nimarezainia** [comment]
so for now I will park these docs related serverless issues until we have the new docs source ready and we can comb through those to *subtract* and add where needed.

**Comment by kilfoyle** [comment]
@joshdover After discussion with @nimarezainia and others, we've decided against creating a separate set of the Fleet & Agent docs for Serverless. The differences between the two sets would be small, and having duplicate content would significantly increase maintenance effort as well as the likelihood of the two docs sets going out of sync.

So, we plan to stick with having the Fleet & Agent docs where they are. In the Serverless docs there's a [Fleet & Agent landing page](https://docs-staging.elastic.dev/serverless/fleet-and-elastic-agent) that essentially points people to the existing docs.

As for restrictions, such as Fleet Server not being supported on Serverless, they've been added to the current docs via https://github.com/elastic/ingest-docs/issues/582 The changes are currently hidden behind a feature flag that I'll enable for the Serverless gated preview on Oct.31. 

I hope that all sounds okay!

**Comment by joshdover** [comment]
SGTM
