### ISSUE TITLE
Include relevant information in Kibana Fleet API Docs.

### ISSUE THREAD

**Issue by jvalente-salemstate** [elastic/ingest-docs#432]
The Kibana Fleet API documentation isn't terribly clear on usage using the Dev Console. 

https://www.elastic.co/guide/en/fleet/current/fleet-api-docs.html

When viewing the [Kibana REST API documentation](https://www.elastic.co/guide/en/kibana/current/api.html), there is a note very early on that explains how to make these calls via the Dev Console

`Prepend any Kibana API endpoint with kbn: and send the request through Dev Tools > Console.`

This note does not seem to included anywhere within the Kibana Fleet API docs.  With the documentation also not even in the same guide as Kibana’s, and with users likely never hitting the Kibana API documentation when looking at Fleet docs, it is not apparent whatsoever that this needs to be specified.  Either linking to the Kibana REST API docs or including the same note at the beginning of the Kibana Fleet API will substantially improve user experience  here.

Having never used Kibana’s APIs, and reading through the ES and Fleet docs, I never came across an explanation as to why nothing worked. I only found the solution by accidentally opening the documentation for the Kibana REST API.

**Comment by kilfoyle** [comment]
Thanks for opening this @jvalente-salemstate! Those instructions definitely were missing.

The [Kibana Fleet APIs page](https://www.elastic.co/guide/en/fleet/current/fleet-api-docs.html) should be updated very soon via #449, after the PR is backported into the current release and then the docs rebuild.
