### ISSUE TITLE
IngestArch: Standardize on a title

### ISSUE THREAD

**Issue by karenzone** [elastic/ingest-docs#435]
The title of this doc has morphed over time. Let's standardize.

<img width="892" alt="Screen Shot 2023-08-28 at 10 28 01 AM" src="https://github.com/elastic/ingest-docs/assets/35154725/d211b6ba-7471-4b89-bf94-d994530014fd">

Options to consider:
- [ ] Elastic Ingest Architectures
- [x] Elastic Ingest Reference Architectures
- [ ] Elasticsearch Ingest Architectures
- [ ] Elasticsearch Ingest Reference Architectures
- [ ] Others?

**Comment by karenzone** [comment]
@nimarezainia, @flexitrev, @strawgate, let's standardize on a title, please. How would you like to go about deciding?

**Comment by nimarezainia** [comment]
I'd vote for "Elastic Ingest Reference Architectures"

**Comment by karenzone** [comment]
Thank you all.  Implemented in #654
