### ISSUE TITLE
IngestArch: Update logstash to elasticsearch graphic to show inputs

### ISSUE THREAD

**Issue by karenzone** [elastic/ingest-docs#55]
Update graphic (`ls-es.png`) to show:
* additional inputs for common use cases
* filter plugins by name 

Action Item: Identify plugins we want to highlight

<img width="753" alt="Screen Shot 2023-02-17 at 5 24 25 PM" src="https://user-images.githubusercontent.com/35154725/219805321-22ba21b3-1c5d-4712-8d38-481d9e0d85e6.png">

**Comment by karenzone** [comment]
@roaksoax @jsvd @mukeshelastic (and trevor)

**Comment by flexitrev** [comment]
We only want to highlight ones that are supported, we should include the link as a reference, not in the image but on the page - https://www.elastic.co/support/matrix#logstash_plugins

Let's keep the list fairly small for simplicity. I think these will be the most relevant

- Input: http, jdbc, kafka, s3
- Filter: cidr, date, geoip, elasticsearch, grok
- Output: elasticsearch

**Comment by karenzone** [comment]
Closed with #57
