### ISSUE TITLE
Publish Fleet and Elastic Agent release notes for 8.7.0

### ISSUE THREAD

**Issue by dedemorton** [elastic/ingest-docs#60]
The process for adding Fleet and Elastic Agent release notes is still in flux. See https://github.com/elastic/observability-docs/issues/703.

But the 8.7.0 release is rapidly approaching. We need to:

* Check in on the current status of the release notes script.
* Decide what format we want to provide for 8.7.0. (For example, do we want to continue duplicating the Fleet release notes, or just point users to the Kibana release notes for Fleet-related items. We will need to publish release notes for Elastic Agent and Fleet Server in some format somewhere.)
* Make sure the release notes get published for 8.7.0.

## Contacts/stakeholders:

@pierrehilbert 
@cmacknz 

cc @kilfoyle

**Comment by pierrehilbert** [comment]
Adding @jen-huang and @kpollich for the Fleet part.
I would like to spend time to have everything using the new fragment system (not the case for Beats yet) and to have a new pipeline that will remove some manual action here.
However, I'm not sure it will be ready for the 8.7 release.

**Comment by kilfoyle** [comment]
@endorama or @cmacknz  Would you be the right folks to ask about running the [elastic-agent-changelog-tool](https://github.com/elastic/elastic-agent-changelog-tool/blob/main/docs/getting-started.md)? If you don't mind running that I'll add the output into the Release Notes PR.

**Comment by cmacknz** [comment]
Here's the YAML changelog summary generated from each of the changelog fragments in the agent repository: https://github.com/elastic/elastic-agent/pull/2395
