### ISSUE TITLE
[REQUEST]: Document "restart upgrade" cooldown for agents

### ISSUE THREAD

**Issue by kpollich** [elastic/ingest-docs#605]
### Description

We want to add a section to the docs somewhere that explains that there's a 10 minute cooldown between forcing a restart of an upgrade for agent to avoid overwhelming the agent.

### Resources

https://github.com/elastic/kibana/pull/168606

### Collaboration

The product team will provide the initial content.

### Point of contact.

**Main contact:** @kpollich 

**Stakeholders:** @elastic/fleet

**Comment by kpollich** [comment]
Thinking maybe we can add a block of text in or around this section: https://www.elastic.co/guide/en/fleet/current/upgrade-elastic-agent.html#upgrade-an-agent or here: https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html#fleet-agent-stuck-on-updating

> If an agent's upgrade appears stuck, you may restart the upgrade process from the Fleet UI. Please note, however, that there is a 10 minute cooldown in between restart attempts.

**Comment by kpollich** [comment]
We link to the "upgrade an agent" docs elsewhere in the "restart upgrade" modal so that's probably the right place.

**Comment by kilfoyle** [comment]
Thanks for opening this @kpollich! I agree that the first page you linked to is the right spot. Here's a [PR](https://github.com/elastic/ingest-docs/pull/609) with that change (note that I had earlier updated the v8.11 and higher docs with the new "restart upgrade" function, so this looks a bit different from your link above). 

By the way, I didn't realize we have a Troubleshooting section about stalled upgrades. I am thinking that with the new, more granular upgrade details shown on the UI and the new restart upgrade option that Julia added, that troubleshooting section may cause some confusion. I think maybe I should remove it from the 8.12 and later docs. What do you think?

**Comment by kpollich** [comment]
+1 on removing those troubleshooting docs and directing users to the restart upgrades docs. Thanks this looks great!
