### ISSUE TITLE
Deprecate Functionbeat docs

### ISSUE THREAD

**Issue by kilfoyle** [elastic/ingest-docs#608]
Functionbeat reaches end of support on Oct.18, 2023. The docs are being updated to indicate that via https://github.com/elastic/beats/pull/36871

We need to deprecate the Functionbeat docs:

 - [x] Freeze the builds at ~~v8.10~~8.15 and move the guide to the "Legacy documentation" part of the docs landing page. ~~https://github.com/elastic/docs/pull/2814~~ https://github.com/elastic/docs/pull/2895
 - [x] ~~Fix [broken links](https://github.com/elastic/docs/pull/2895) caused by freezing. ← ON HOLD. Links from UI are being fixed.~~ Instead we removed Functionbeat from kbn-doc-links via https://github.com/elastic/kibana/pull/198902
 - [x] Update the [main Functionbeat docs page].(https://www.elastic.co/guide/en/beats/functionbeat/current/functionbeat-overview.html) with a notice and a link to the Elastic Serverless Forwarder Guide. https://github.com/elastic/beats/pull/37021

Rel: https://github.com/elastic/ingest-dev/issues/1251

**Comment by lucabelluccini** [comment]
As reported from users - the fact we update docs and we publish statements such as `Version 8.15.2 supports deploying Functionbeat as an AWS Lambda servic....` is adding confusion.

**Comment by kilfoyle** [comment]
Thanks @lucabelluccini! I've followed up in the Integrations channel in Slack to see if I can get some traction on [this issue](https://github.com/elastic/kibana/issues/194039). 
@nimarezainia just FYI.

**Comment by AndersonQ** [comment]
@nimarezainia, https://github.com/elastic/beats/issues/40745 is about removing it only for 9.0. I was talking to @kilfoyle over slack and we were unsure if the docs should be kept for 8.16 and 8.x or not.

**Comment by kilfoyle** [comment]
Functionbeat docs are now frozen at 8.15 and moved to the "Legacy docs" section of the main docs page, via https://github.com/elastic/docs/pull/2895

Thanks so much for your help with this @AndersonQ!
