### ISSUE TITLE
IngestArch: Organize and track implementation of review comments

### ISSUE THREAD

**Issue by karenzone** [elastic/ingest-docs#62]
Related: #56 

* [x] #61 

#### [Elastic Agent to Elasticsearch: Agent installed](https://www.elastic.co/guide/en/ingest/current/agent-installed.html)
* [x] In this [doc](https://github.com/elastic/ingest-docs/edit/main/docs/en/ingest-arch/1a-agent.asciidoc), not sure what it means to say `(agent installed)` (in the ingest model->data path section)
* [x] An Elastic Agent integration exists in the Kibana integrations UI for software components on which you can install Elastic Agent`, one can understand that if he wants to ingest nginx logs, the elastic agent should be installed on the nginx "software component", which is not the case. I would rephrase it to something more simple like "An Elastic Agent integration exists in the Kibana integrations UI for the software you want to monitor / observe / protect.
* [x] Examples list is still empty. Why? Should be relatively easy to fetch from our telemetry.

### [Elastic Agent to proxy to Elasticsearch](https://www.elastic.co/guide/en/ingest/current/agent-proxy.html)
* [x] In [this](https://www.elastic.co/guide/en/ingest/current/agent-proxy.html) doc i would make it clear in the diagram what's the control path and what's the data path.
* [x]  in the same [document](https://www.elastic.co/guide/en/ingest/current/agent-proxy.html), the control and data paths are mixed. Fleet server is not in the data path.
* [x]  same document. typo: `preventconnection`
* [x]  I would love if @cmacknz can double check what's written [here](https://www.elastic.co/guide/en/fleet/master//fleet-agent-proxy-support.html) on proxy configuration
   * From @cmacknz: It's correct, the only thing we should we should note is that if the user a needs a proxy specifically for connects to artifacts.elastic.co (separate from the Fleet Server proxy and the Elasticsearch proxy) they can configure it by setting the proxy URL in [Agent Binary Download Settings](https://www.elastic.co/guide/en/fleet/master//fleet-settings.html#fleet-agent-binary-download-settings).   
   * Tracked in #69 for followup.
* [x]  do we also want to say something about client certs and mTLS? @nimarezainia 
   * See [comment](https://github.com/elastic/ingest-docs/issues/62#issuecomment-1489544939). Tracked in #69 for followup.

### [Elastic Agent to Logstash to Elasticsearch](https://www.elastic.co/guide/en/ingest/current/agent-ls.html)
* [x]  well done on the logstash use cases!  :-) 

### Update: Logstash use case content moved to #70 for tracking and resolution

~#### [Elastic Agent to Logstash (for enrichment) to Elasticsearch](https://www.elastic.co/guide/en/ingest/current/ls-enrich.html)~
~* [ ]  On the enrichment [doc](https://www.elastic.co/guide/en/ingest/current/ls-enrich.html), i would link to a few enrich processors we have (there's a link at the bottom to "Transform" which is a bit different than just "enrich")~
~* [ ]  "Data sources that change frequently, such as stock ticker data" - why is this an example to use Logstash? does it imply that Agent is not fast enough? or is it because the enriched data is "public" data source and thus we need Logstash's custom HTTP/tcp input plugin?~
~* [ ] in [this](https://www.elastic.co/guide/en/ingest/current/ls-enrich.html#ls-enrich-proc) process overview, worth adding how to configure logstash as an output to Agent? (in the agent policy UI)~
~* [ ] Same thing for all 4 Agent to LS documents~

~##### [Elastic Agent to Logstash to Elasticsearch: Logstash Persistent Queue (PQ) for buffering](https://www.elastic.co/guide/en/ingest/current/lspq.html)~
~* [ ] We have some PQ performance benchmarks today. @roaksoax should we link it [here](https://www.elastic.co/guide/en/ingest/current/lspq.html)?~

~##### [Elastic Agent to Logstash to Elasticsearch: Logstash to bridge networks]~(https://www.elastic.co/guide/en/ingest/current/ls-networkbridge.html#ls-networkbridge)~
~* [ ] Worth adding a visual in the [diagram](https://www.elastic.co/guide/en/ingest/current/ls-networkbridge.html) to show the two different networks that LS is used to bridge between.~
~* [ ] "Use when"... the same explanation was given to put a proxy between agents and ES, so what makes this use case unique to use Logstash?~
~* [ ] Examples are missing...~
* [x] we will soon need to update [this](https://www.elastic.co/guide/en/ingest/current/ls-for-input.html) doc because LS can be deployed on k8s as well (ECK). I would just avoid specifying the host for the logstash instance, not sure what value it adds.

#### Global questions and comments
* [x] (relevant to all docs) Can we add an animated gif to show the installation flow? perhaps a link to a webinar / youtube video? 
  * Tracked in #69 for followup.

**Comment by nimarezainia** [comment]
> * do we also want to say something about client certs and mTLS? 

@karenzone We currently don;t have full support for this. Should be able to soon. but certainly a good idea to add it to this document.

**Comment by karenzone** [comment]
Closing out Sprint 9, and moving unresolved items to new issues for research, tracking, and resolution: 
* #69 
* #70
