### ISSUE TITLE
[REQUEST]: Document new ingest pipeline extension points in Fleet

### ISSUE THREAD

**Issue by kpollich** [elastic/ingest-docs#638]
### Description

In https://github.com/elastic/kibana/pull/170270 we extended the set of "extension points" for ingest pipelines that are included in Fleet's default component templates:

- `global`
- `${type}`
- `${type}-${package}`
- `${type}-${dataset}`

We should update https://www.elastic.co/guide/en/fleet/8.10/data-streams-pipeline-tutorial.html to mention these extension points for various levels of customization. Processors can be added globally, for all logs or all metrics, for an entire integration, or for a specific dataset. 

### Resources

- https://github.com/elastic/kibana/pull/170270
- https://www.elastic.co/guide/en/fleet/8.10/data-streams-pipeline-tutorial.html

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @nchaulet + @kpollich 

**Stakeholders:**: @elastic/fleet

**Comment by kilfoyle** [comment]
Thanks for opening this @kpollich. Could you or @nchaulet possible provide an example or a demo of some sort? These pipelines are completely new to me so I'd need a bit of help to document this. I will try out the tutorial to get caught up.

**Comment by nchaulet** [comment]
@kilfoyle I can try to explain a little more what the feature do here, let me know if it's enough or if we should schedule a demo,

Ingest pipelines[edit](https://github.com/elastic/elasticsearch/edit/8.10/docs/reference/ingest.asciidoc) allow you to modify your data before them being indexed in elasticsearch.
For each Fleet managed datastream we have a managed ingest pipeline and we allow the user to register a custom one that will be called after the fleet default one.
We used to support the `${type}-${dataset}@custom` one that allowed to override the pipeline for a specific datastream, but we now support different level `global@custom` that will be called for every fleet managed datastream, or `logs@custom` that will be called for every logs managed by fleet.

For example creating the following ingest pipeline will result in every new logs event for fleet managed datastream to have the field "test:tata"

```
PUT _ingest/pipeline/logs@custom
{
  "processors": [
    {
      "set": {
        "description": "test",
        "field": "test",
        "value": "tata"
      }
    }
  ]
}
```

**Comment by kilfoyle** [comment]
That is perfect. Thanks a lot @nchaulet! I think I should have enough info now, but in case I have any questions I'll let you know.

**Comment by ruflin** [comment]
Glad to see these docs get updated. One thing I stumbled over when reviewing is, this is under `Manage Elastic Agents in Fleet` but AFAIK know nothing of this requires a Fleet managed Elastic Agent, this is about the integrations. Anecdotally, I have several times heard in the past that all these features are only available with managed elastic agent which is not the case, I think the location of these docs contribute to the confusion.

**Comment by kilfoyle** [comment]
@ruflin Good point! Do you think it would solve things if I relocate this "Data streams" section out of "Manage Elastic Agents in Fleet" and put it under "Manage integrations"?  Alternately, I could make it a section of its own, similar to "Define processors".

![Screenshot 2023-11-02 at 9 14 37 AM](https://github.com/elastic/ingest-docs/assets/41695641/2300f920-5f84-4388-a9e9-aabd6b71258a) 
![Screenshot 2023-11-02 at 9 16 10 AM](https://github.com/elastic/ingest-docs/assets/41695641/39fe60b7-a90a-4efb-bedb-6afd87b6ad2b)

**Comment by ruflin** [comment]
I think that would fit well under "Manage integrations". 

Nit: I would also put manage integrations under "Configure standalone Elastic Agent" or on top of "Manage Elastic Agent in Fleet". These two kind of belong together and it is odd that "Manage integrations" is in the middle, it also indicates it belongs somehow to fleet managed.
