### ISSUE TITLE
[Fleet]: Screenshot not updated for Integrations tab as `View deployment details` updated to `Endpoints`.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#660]
**Description:**
Screenshot not updated for Integrations tab as `View deployment details` updated to `Endpoints` on latest 8.11.0.

**Link(s):**
https://www.elastic.co/guide/en/fleet/current/fleet-overview.html

**Actual Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/9636c3a4-37b3-4389-b859-257bfa2ffd94)

**Expected Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/b445ee38-40ff-41a6-ad24-bd4772dc06a4)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by amolnater-qasource** [comment]
FYI @kilfoyle

**Comment by kilfoyle** [comment]
@amolnater-qasource  This will be fixe by #1011. I notice that that `View deployment details` link changed to `Endpoints` for 8.11, but then it changed again to `Connection details`, I think starting in 8.12. So I've used the latest version of the UI for the new screenshot.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated the docs for 8.14.0 release and found that they are **updated now**.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/fleet-overview.html

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/faebc746-56f7-4861-a380-0e3df3a00730)


Hence, we are marking this as **QA:Validated**.

Thanks!
