### ISSUE TITLE
[Fleet]: Edit Agent policy tab screenshot is outdated.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#661]
**Description:**
Edit Agent policy tab screenshot is outdated as per the latest 8.11 build.

**Link(s):**
https://www.elastic.co/guide/en/fleet/current/beats-agent-comparison.html

**Actual Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/4c825c91-5dc1-4739-96ac-8b3b859c6c62)

**Expected Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/33940077-ef7a-4565-9ff1-2092c5d5a970)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
FYI @kilfoyle

**Comment by kilfoyle** [comment]
Ah, found it! The link with that outdated graphic is here, in the Fleet & Agent Guide:
https://www.elastic.co/guide/en/fleet/current/beats-agent-comparison.html

I will transfer this issue back to the ingest-docs repo that contains that guide.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated the docs for 8.14.0 release and found that they are **updated now**.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/beats-agent-comparison.html#agent-monitoring-support

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/6cb18286-e808-4f0d-823f-02d834d2225d)

Hence, we are marking this as **QA:Validated**.

Thanks!
