### ISSUE TITLE
[Fleet]: Uninstalled token tab is missing under agents tab in screenshots.

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/ingest-docs#662]
**Description:**
Uninstalled token tab is missing under agents tab in screenshots.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/install-fleet-managed-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/current/fleet-overview.html
- https://www.elastic.co/guide/en/fleet/current/agent-policy.html
- https://www.elastic.co/guide/en/fleet/current/migrate-beats-to-agent.html
- https://www.elastic.co/guide/en/fleet/current/upgrade-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/current/migrate-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/current/monitor-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/current/data-streams.html
- https://www.elastic.co/guide/en/fleet/current/elastic-agent-container.html
- https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-managed-by-fleet.html
- https://www.elastic.co/guide/en/fleet/current/scaling-on-kubernetes.html

**Actual Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/101545338/7673d5d8-ad45-417a-8d03-e31c98904243)

**Expected Result**
![image](https://github.com/elastic/ingest-docs/assets/101545338/b5d670ac-b96d-42f1-9698-13120aab156f)

**Comment by harshitgupta-qasource** [comment]
@amolnater-qasource Kindly review

**Comment by amolnater-qasource** [comment]
Secondary review is done for this ticket.

FYI @kilfoyle

**Comment by harshitgupta-qasource** [comment]
Hi Team,

We have revalidated the docs for 8.14.0 release and found that they are **updated now**.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/install-fleet-managed-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/current/fleet-overview.html
- https://www.elastic.co/guide/en/fleet/current/agent-policy.html
- https://www.elastic.co/guide/en/fleet/current/migrate-beats-to-agent.html
- https://www.elastic.co/guide/en/fleet/current/upgrade-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/current/migrate-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/current/monitor-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/current/data-streams.html
- https://www.elastic.co/guide/en/fleet/current/elastic-agent-container.html
- https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-managed-by-fleet.html
- https://www.elastic.co/guide/en/fleet/current/scaling-on-kubernetes.html

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/101545338/63c397a3-b05d-4a08-9e5e-5984fc9cf120)

Hence, we are marking this as **QA:Validated**.

Thanks!
