### ISSUE TITLE
[Fleet]: Uninstall agent in action menu is missing under agents tab screenshot.

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/ingest-docs#664]
**Description:**
Uninstall agent in action menu is missing under agents tab screenshot.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/agent-policy.html
- https://www.elastic.co/guide/en/fleet/current/upgrade-elastic-agent.html
- https://www.elastic.co/guide/en/fleet/current/filter-agent-list-by-tags.html
- https://www.elastic.co/guide/en/fleet/current/agent-policy.html

**Actual Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/101545338/66fc08da-73dc-4ba0-ad45-ce167793574b)

**Expected Result**
![image](https://github.com/elastic/ingest-docs/assets/101545338/dc097552-6c1b-4cea-8b76-f9ede8c01d05)

**Comment by harshitgupta-qasource** [comment]
@amolnater-qasource Kindly review

**Comment by kilfoyle** [comment]
Thanks for opening this @harshitgupta-qasource 

I've updated the screenshots showing the Agent actions menu. Please note that there are two different menus: one from the "Actions" button in Fleet, and one from the "..." symbol beside any agent. The "Uninstall agent" action is available only from the "..." menu shown in your second screenshot.

Anyhow, I've updated all of them so hopefully they're okay now. :-)

**Comment by harshitgupta-qasource** [comment]
Hi Team,

We have revalidated the docs for 8.14.0 release and found that they are **updated now**.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/upgrade-elastic-agent.html

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/101545338/f305b359-2b75-428a-b7c8-26f67991417d)


Hence, we are marking this as **QA:Validated**.

Thanks!
