### ISSUE TITLE
[Fleet]: Edit Output Flyout screenshot not having yellow caution label.

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/ingest-docs#665]
**Description:**
Edit Output Flyout screenshot not having yellow caution label.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/fleet-agent-proxy-managed.html

**Actual Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/101545338/4d4ddade-9a3c-4d84-ae58-e2591868e27b)

**Expected Result**
![image](https://github.com/elastic/ingest-docs/assets/101545338/a0264762-8c73-4bc5-a5db-d568783aaee4)

**Comment by harshitgupta-qasource** [comment]
@amolnater-qasource Kindly review

**Comment by amolnater-qasource** [comment]
Secondary review is done for this ticket.

FYI @kilfoyle

**Comment by harshitgupta-qasource** [comment]
Hi Team,

We have revalidated the docs for 8.14.0 release and found that they are **updated now**.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/fleet-agent-proxy-managed.html

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/101545338/8f19f7d0-ea93-4349-9684-4fcf515279bc)


Hence, we are marking this as **QA:Validated**.

Thanks!
