### ISSUE TITLE
[Fleet]: The aforementioned screenshot for Cloud ID displays browser bookmarks.

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/ingest-docs#666]
**Description:**
The aforementioned screenshot for Cloud ID displays browser bookmarks..

**Link:**
- https://www.elastic.co/guide/en/fleet/current/elastic-agent-container.html

**Actual screenshot:**

![image (14)](https://github.com/elastic/ingest-docs/assets/101545338/b9a18674-707b-446f-9af6-1a9bb4039d60)

**Expected Result**
Bookmarks should be removed from this mentioned screenshot

**Comment by harshitgupta-qasource** [comment]
@amolnater-qasource Kindly review

**Comment by amolnater-qasource** [comment]
Secondary review is done for this ticket.

FYI @kilfoyle

**Comment by harshitgupta-qasource** [comment]
Hi Team,

We have revalidated the docs for 8.14.0 release and found that they are **updated now**.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/migrate-elastic-agent.html#migrate-elastic-agent-fleet-host

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/101545338/9c5a8069-fd11-4db8-9168-d66445350890)


Hence, we are marking this as **QA:Validated**.

Thanks!
