### ISSUE TITLE
[Fleet]: Diagnostics tab not available under Agent logs tab screenshot.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#669]
**Description:**
Diagnostics tab not available under Agent logs tab screenshot.

**Link(s):**
https://www.elastic.co/guide/en/fleet/current/monitor-elastic-agent.html

**Actual Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/2de67caf-0ff0-4acd-91d9-9f4d364e8a2a)

**Expected Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/f279a142-f866-4db0-b57f-f91404b41b0a)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated the docs for 8.14.0 release and found that they are **updated now**.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/monitor-elastic-agent.html#view-agent-logs

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/bf641776-6290-494d-9cf0-9893b6f87954)


Hence, we are marking this as **QA:Validated**.

Thanks!
