### ISSUE TITLE
[Fleet]: Message under Diagnostics tab is not updated as per 8.11

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#670]
**Description:**
Message under Diagnostics tab is not updated as per 8.11

**Link(s):**
https://www.elastic.co/guide/en/fleet/current/monitor-elastic-agent.html

**Actual Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/656afc91-5c4b-4b86-8ff5-5d3330c64ca7)

**Expected Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/238727f3-7689-4048-9e87-07d27d64c427)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
FYI @kilfoyle

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated the docs for 8.14.0 release and found that they are **updated now**.

**Link:**
- https://www.elastic.co/guide/en/fleet/current/monitor-elastic-agent.html#collect-agent-diagnostics

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/e1bb7108-4c16-434d-9ffb-c1622ae7e349)


Hence, we are marking this as **QA:Validated**.

Thanks!
