### ISSUE TITLE
[Elastic Agent] Document Kafka Output UI for fleet managed agents

### ISSUE THREAD

**Issue by jlind23** [elastic/ingest-docs#68]
This is a placeholder in order to document the Kafka output options that will be available for the Elastic Agent and configurable via Fleet.

**Comment by karenzone** [comment]
Related dev issues are slated for S13 (https://github.com/elastic/kibana/issues/143324) and S14 (https://github.com/elastic/ingest-dev/issues/1173).  Moving this issue to S13 to track with Dev work.

**Comment by kilfoyle** [comment]
For reference, Fleet UI changes to support Kafka output: https://github.com/elastic/kibana/pull/160112

**Comment by nimarezainia** [comment]
Hi @kilfoyle, as you can see the code for the UI was merged. A nice video showing the options also. We still have time until 8.10 but wanted to see how I can help wit the documentation. In particular my focus is mainly on a list of Beta candidates that I want to reach out to and would need to point them at documentation in that 8.10 time frame.

**Comment by kilfoyle** [comment]
Hi @nimarezainia  Thanks a lot for the offer! I think I have what I need to put together the docs. Your [requirements definition](https://docs.google.com/document/d/1SIyfL8lhdeUMsrm0gFHI0Uc8LhNV0aynOYz05O6ZYb8/edit?pli=1) is very helpful, as is that UI video. I hope to get a docs PR open within the next couple of weeks so I'd appreciate your review once it's ready, and I'll certainly be in touch if any questions come up along the way.

**Comment by kilfoyle** [comment]
Kafka output settings docs are available in the 8.10 docs: https://www.elastic.co/guide/en/fleet/master/kafka-output-settings.html

**Comment by amitkanfer** [comment]
Thanks @kilfoyle !
Few comments from me:

1. Should we make sure to instruct the user to choose "Kafka" in the output type?
<img width="633" alt="image" src="https://github.com/elastic/ingest-docs/assets/2217774/815e2986-cb70-4cbd-b451-043404149cbc">

2. Regrading the version field - why do we default to 1.0.0 in the product? I see it also in the [RFC](https://docs.google.com/document/d/1SIyfL8lhdeUMsrm0gFHI0Uc8LhNV0aynOYz05O6ZYb8/edit) but w/o explanation. (question to @nimarezainia i guess)

3. Can we have `Server SSL certificate authorities` and `Verification mode` to be links to the right places in the docs? (same is true to other places that make sense)

4. In the `Username / Password` field, why don't we document the different authentication types? What does each entry provide? how should the user know what auth type he's using?
<img width="186" alt="image" src="https://github.com/elastic/ingest-docs/assets/2217774/6472b4d0-52c7-4c89-a5e3-2f8fcde10110">

5. We should probably remove the `none` option in the compression codec options. If the user enabled compression, it doesn't make sense to then choose `none` in the dropdown.
<img width="635" alt="image" src="https://github.com/elastic/ingest-docs/assets/2217774/4a64b505-2ab5-4c54-842d-aa10c02a2f99">

6. @nimarezainia, @kevinlog - Should we group the "other settings" in a grey panel div in the product? these settings seem to be "hanging in there". We should at least add a title - ("Other settings"). I was looking to which section the `key (optional)` belongs to.

7. @nimarezainia @kevinlog - whould we add a reference link to the [docs](https://www.elastic.co/guide/en/fleet/master/kafka-output-settings.html) from the product itself? (simple `i` or `?` icons or anything else you think will work out)

8. In `Other Settings`->`Key` documentation, we're sending the user to the kafka docs i believe, would be great to a add a link.
<img width="827" alt="image" src="https://github.com/elastic/ingest-docs/assets/2217774/2ce744b6-6f44-4f07-aed0-f85a4df319e6">

Thanks

**Comment by nimarezainia** [comment]
1) Yes I think this is a good idea. We actually don't do it for other output types. Perhaps a separate followup.

2) In this case we asked for the 1.0.0 default mainly because that is what we do for Beats.

3) I am not sure if one exists (we created this for Logstash which has the same concern: https://www.elastic.co/guide/en/fleet/master/secure-logstash-connections.html)

4) @kilfoyle the explanations are something like what I have below (although I don't see this anywhere in our docs):
- SCRAM-SHA256 / SCRAM-SHA512 --> When enabled Agent uses SCRAM to authenticate the user credential. SCRAM is based on the IETF RFC5802 standard which describes a challenge-response mechanism for authenticating users.
- SCRAM-SHA256 is using SHA-256 hashing function where as SCRAM-SHA512 uses SHA-512

[@cmacknz @faec please keep me honest on this]

**Comment by nimarezainia** [comment]
5. Good catch. I opened: https://github.com/elastic/ingest-dev/issues/2327 to address.

6.  this was the UX designer recommendation. Proxy and the YAML box are standard for all outputs, so i wouldn't want to hide them in any way. Yes "Key" didn't really fit in any category. I'd say if we start adding more params, we should consider an Advanced  section.

7. There's a "learn more" at the top of the page. Do you mean links within the product for each section of the doc? I think we can do this but we should also apply the same to other outputs.

**Comment by nimarezainia** [comment]
> 13\. In `Other Settings`->`Key` documentation, we're sending the user to the kafka docs i believe, would be great to a add a link.
> 
> 
> <img alt="image" width="827" src="https://user-images.githubusercontent.com/2217774/261850873-2ce744b6-6f44-4f07-aed0-f85a4df319e6.png">

@cmacknz @faec would you know where we can create a pointer to kafka docs ? I don't see any references in the docs aside from blog posts, which honestly are more descriptive than a reference manual. This being a good one: https://kafka.apache.org/intro#intro_topics

any thoughts about pointing that blog?

**Comment by kevinlog** [comment]
Thanks @amitkanfer @nimarezainia for the discussion.

> 7. @nimarezainia @kevinlog - would we add a reference link to the [docs](https://www.elastic.co/guide/en/fleet/master/kafka-output-settings.html) from the product itself? (simple `i` or `?` icons or anything else you think will work out)

> 7. There's a "learn more" at the top of the page. Do you mean links within the product for each section of the doc? I think we can do this but we should also apply the same to other outputs.

Here's the "Learn more" docs link for the Kafka output.  It follows a similar pattern as Logstash.  Is the ask that we make this link more prominent?

<img width="687" alt="image" src="https://github.com/elastic/ingest-docs/assets/56395104/17b82b79-d0cd-47ec-b9a3-f3316bc9e2ef">

> 6. @nimarezainia, @kevinlog - Should we group the "other settings" in a grey panel div in the product? these settings seem to be "hanging in there". We should at least add a title - ("Other settings"). I was looking to which section the `key (optional)` belongs to.

> 6.  this was the UX designer recommendation. Proxy and the YAML box are standard for all outputs, so i wouldn't want to hide them in any way. Yes "Key" didn't really fit in any category. I'd say if we start adding more params, we should consider an Advanced  section.

I agree with Nima, we could wait for more params and then organize into an Advanced section or whatever the next UX recommendation is.

> 5. We should probably remove the `none` option in the compression codec options. If the user enabled compression, it doesn't make sense to then choose `none` in the dropdown.

Thanks Nima for filing https://github.com/elastic/ingest-dev/issues/2327 - I think it should be straightforward.

***Action items for 8.10***

At this point, I see two action items for the product itself:
- Potentially move the docs link to be more prominent (or in a `?` or `!`).
- Remove `none` option for compression - https://github.com/elastic/ingest-dev/issues/2327

Let me know if I've missed anything.

**Comment by cmacknz** [comment]
> @cmacknz @faec would you know where we can create a pointer to kafka docs ? I don't see any references in the docs aside from blog posts, which honestly are more descriptive than a reference manual. This being a good one: https://kafka.apache.org/intro#intro_topics

That link is fine, the diagram included is particularly good for explaining how this works.

**Comment by kilfoyle** [comment]
> Potentially move the docs link to be more prominent (or in a ? or !).

@kevinlog In the Logstash and Kafka and output settings UI the docs "Learn more" link points to [here](https://www.elastic.co/guide/en/fleet/current/fleet-settings.html). I've created new docs pages specifically for Logstash and Kafka outputs, so ideally those links could be updated to point to `/ls-output-settings.html` and `/kafka-output-settings.html` respectively. I was going to open a PR for that myself but I haven't investigated yet where those links are defined, so if you have any idea I'd appreciate your help.

**Comment by kilfoyle** [comment]
Thanks @amitkanfer and @nimarezainia for the feedback and suggestions.

1. Should we make sure to instruct the user to choose "Kafka" in the output type?

Fixed as shown. I made a similar change to the Logstash and Elasticsearch output pages:
![Screenshot 2023-08-21 at 11 32 35 AM](https://github.com/elastic/ingest-docs/assets/41695641/2fc4ad71-0b04-4368-879f-dc8a54d7de2b)


4. In the Username / Password field, why don't we document the different authentication types? What does each entry provide? how should the user know what auth type he's using?

Thanks @nimarezainia for the descriptions. I've updated as shown. The link points to the [SCRAM wiki page](https://en.wikipedia.org/wiki/Salted_Challenge_Response_Authentication_Mechanism).

![Screenshot 2023-08-21 at 11 35 02 AM](https://github.com/elastic/ingest-docs/assets/41695641/5a7e8d6a-b7a6-4126-9be8-55f9e4ace565)


8. In Other Settings->Key documentation, we're sending the user to the kafka docs i believe, would be great to a add a link.

As suggested, I've made this a link to https://kafka.apache.org/intro#intro_topics
![Screenshot 2023-08-21 at 11 24 14 AM](https://github.com/elastic/ingest-docs/assets/41695641/51e2c5de-f63f-4534-ad70-a7c7271d70da)

For number 3.:
>Amit: Can we have Server SSL certificate authorities and Verification mode to be links to the right places in the docs?
>Nima: I am not sure if one exists (we created this for Logstash which has the same concern: https://www.elastic.co/guide/en/fleet/master/secure-logstash-connections.html)

I can create a new Kafka Secure Connections page equivalent to the [Logstash Secure Connections](https://www.elastic.co/guide/en/fleet/master/secure-logstash-connections.html) page if anyone can help me with the content. I assume the two pages would be pretty similar.

**Comment by kevinlog** [comment]
@kilfoyle I was going to link the changes you would need to make, but it was easier to just make the PR :).  Could be used as a future reference.

here's the PR to update the docs links: https://github.com/elastic/kibana/pull/164335

**Comment by kilfoyle** [comment]
> @kilfoyle I was going to link the changes you would need to make, but it was easier to just make the PR :). Could be used as a future reference.

Nice. Thanks @kevinlog! Now that I know how I can open a PR myself for next time.
