### ISSUE TITLE
[Fleet]: Warn using --base-path might prevent Elastic Agent to work when used with specific integrations

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/ingest-docs#688]
### Description

In Elastic Agent, using a custom `--base-path` might be incompatible with other integrations (afaik, Elastic Defend).
See https://github.com/elastic/elastic-agent/issues/2599

We should put a warning there if it is still the case.
We should also clarify which cli params are allowed in managed vs standalone Elastic Agent.

### Resources

See description.

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @cmacknz / @lucabelluccini 

**Stakeholders:**

**Comment by cmacknz** [comment]
> We should put a warning there if it is still the case.

Where is the best place for this warning to go? AFAIK only Elastic Defend is incompatible with the --base-path flag.

> We should also clarify which cli params are allowed in managed vs standalone Elastic Agent.

Is there a specific example, wondering if this is just a bug.

**Comment by lucabelluccini** [comment]
> Where is the best place for this warning to go? AFAIK only Elastic Defend is incompatible with the --base-path flag.

From user perspective, Elastic Agent is often seen as a monolith even if it is not true.
As Elastic Defend is a quite common integration, we should attempt to warn users who might be searching through our docs for customizations. 
I agree adding Elastic Defend here might be risky in terms of maintenance (we need to remember to update this section if the limitation will go away), but it is better to warn users in advance instead of letting them use the flag and then find out the Elastic Agent will be unhealthy.

> Is there a specific example, wondering if this is just a bug.

If all params/flags of `elastic-agent` cli apply to both standalone and managed, we should maybe state it explicitly in https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html#elastic-agent-install-command.

**Comment by kilfoyle** [comment]
Thanks for the suggestions! I've opened https://github.com/elastic/ingest-docs/pull/699
