### ISSUE TITLE
[Fleet] Document output secrets

### ISSUE THREAD

**Issue by jillguyonnet** [elastic/ingest-docs#692]
This is a followup to https://github.com/elastic/ingest-docs/issues/161 which documented how Fleet handles secret in agent policies.

The scope of [secret storage phase 1](https://github.com/elastic/kibana/issues/154715) also includes storing secrets that exist in outputs: https://github.com/elastic/kibana/issues/157458.

### Details

At this time, output secrets are one of the following:
- Kafka output password
- Kafka output SSL key
- Logstash output SSL key
- Remote ES service token

There are two ways secret values can be set for outputs:
- UI (see https://github.com/elastic/kibana/pull/169429 for screenshots): on creating an output, the user can use a secret (default) or opt to use plain text instead.
- Preconfigured outputs from the Kibana config file (https://github.com/elastic/kibana/issues/166360): a secure hash of the secret value obtained with the Argon2id algorithm is stored in the output's saved object in order for Kibana to manage updates of the secret. At no point is the value itself stored in Kibana.

**Comment by jillguyonnet** [comment]
Adding [remote ES outputs](https://github.com/elastic/kibana/pull/171875) to this.
cc @juliaElastic

**Comment by kilfoyle** [comment]
Completed via [PR](https://github.com/elastic/kibana/pull/172637), [PR](https://github.com/elastic/ingest-docs/pull/696), [PR](https://github.com/elastic/ingest-docs/pull/762)

Thanks a lot for all the help, Jill!
