### ISSUE TITLE
Review and fix API key config docs for standalone agent

### ISSUE THREAD

**Issue by kilfoyle** [elastic/ingest-docs#697]
We need to improve our standalone agent configuration docs with details on how an API key should be created with the correct, restricted set of permissions.

Rel: #693 (about changing basic auth examples to use API keys).

See comments in #655 for details.

---

From Nima:

Here what ruflin rightly is asking for (imo) is an extension to the idea of helping users to create their own configuration. We currently don't have any instruction for the user on how an API key should be created with the restricted permissions. I think we can enhance our current set of configuration examples with [API creation](https://www.elastic.co/guide/en/elasticsearch/reference/8.10/security-api-create-api-key.html) (tutorial? for lack of a better word). For the most part the pattern is there on how to create these, similar to how the anatomy of the standalone configuration was broken down. Docs on API creation do explain it pretty well, but still I reckon it's difficult to create an API key with limited permission.

As an example this is the relevant section for the nginx logs that the user would need to create:

```
"indices": [
  {
    "names": [
      "logs-nginx.access-default"
    ],
    "privileges": [
      "auto_configure",
      "create_doc"
    ],
    "allow_restricted_indices": false
  },
  {
    "names": [
      "logs-nginx.error-default"
    ],
    "privileges": [
      "auto_configure",
      "create_doc"
    ],
    "allow_restricted_indices": false
  },
```

Let's add this to the list if you don't mind and I can get the content to you. We can figure where is the best location for it in the docs.

---

From Nicolas:

To simplify things for standalone, I would recommend users to just create API keys for `logs-*-*` and not specific to the dataset. Otherwise each time they change a config on the edge, the API key might fail. To go broader, we could add `metrics-*-*` to it too.

**Comment by kilfoyle** [comment]
I've discovered that we have a [Grant standalone Elastic Agents access to Elasticsearch](https://www.elastic.co/guide/en/fleet/current/grant-access-to-elasticsearch.html) page, so perhaps we can point to that page from the configuration examples.

**Comment by nimarezainia** [comment]
Might need to review that page. Just went through it and for the most part it does match what we have in code. the api creation is a bit different in the product so perhaps just needs an update. the last snippet is using username/password however.
