### ISSUE TITLE
[REQUEST]: Document the privileges needed for Fleet and Integrations

### ISSUE THREAD

**Issue by criamico** [elastic/ingest-docs#724]
### Description

Recently we've received several requests (in SDHs and other places) to document how to setup roles and privileges for running Fleet and integrations. The privileges system in Fleet changed with 8.0.0 but I'm not sure if it was ever created a specific docs page to explain it.

So I think we should document:
- What privileges are needed for a user the wants to run Fleet & Integrations. This is for a user that is not superuser.
  - Privileges for a role can be "all", "read" and "none", we should explain what they mean and the error messages that the user receives when they're not set properly
 - What are the privileges needed for our API call (see this [SDH](https://github.com/elastic/sdh-beats/issues/4131)), as we allow certain api calls only to some roles, however this is not documented anywhere. I'll open an issue to change it on openapi specs and then it can be updated on https://www.elastic.co/guide/en/fleet/8.11/fleet-apis: https://github.com/elastic/kibana/issues/172155
  

### Current docs
Currently I could only find a line on the [docs](https://www.elastic.co/guide/en/fleet/current/manage-agents-in-fleet.html) 
> Fleet currently requires a Kibana user with All privileges on Fleet and Integrations. Since many Integrations assets are shared across spaces, users need the Kibana privileges in all spaces.

I think we should expand it to a separate page as it doesn't seem very clear to user what this means.

Some explanation about the privilege system for Fleet is in the original PR (it was introduced in 8.1): https://github.com/elastic/kibana/issues/108252#issuecomment-1067820328. Feel free to contact me for further explanations.

### How to create a role for fleet:
![Screenshot 2023-11-20 at 12 00 25](https://github.com/elastic/ingest-docs/assets/16084106/3c38aea8-9d01-4c05-abb8-1926a07f26bd)
![Screenshot 2023-11-20 at 12 00 33](https://github.com/elastic/ingest-docs/assets/16084106/ab96dd75-024e-404a-9458-851033cd60a0)

Also, the `viewer` and `editor` built-in roles grant similar privileges:

- `Editor` role behaves like Fleet > All, Integrations > All
- `Viewer` role behaves like Fleet -> None, Integrations -> Read

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @

**Stakeholders:**

**Comment by leandrojmp** [comment]
Hello, is there any update on this?

We need to know what are the privileges needed by a user to be able to access Fleet Server since we do not want to make everyone a superuser, I couldn't find any documenation on this.

**Comment by kilfoyle** [comment]
@leandrojmp I'm very sorry but I won't be able to look at this issue to update the documentation until mid-January. 

Until then, perhaps @criamico can provide some guidance.

**Comment by leandrojmp** [comment]
@kilfoyle @criamico Hello, is there any update on this?

We are building an automation to manage fleet agents and need to know what are the required privileges, we asked support and got an answer that we needed to add the _All_ privilege on all spaces on Kibana for the user we want to use, we did that but we are getting 401 when trying to use a POST request to an endpoint like `bulk_reassign`, the GET requests are working as expected.

The support case is `#01530414`

**Comment by leandrojmp** [comment]
Hello @kilfoyle is there any update on this?

**Comment by kilfoyle** [comment]
Thanks for the reminder @leandrojmp and apologies for the delay. I've opened up [this PR](https://github.com/elastic/ingest-docs/pull/868). 

@criamico The above PR updates the regular Fleet & Agent docs. For the [Fleet API docs](https://www.elastic.co/guide/en/fleet/current/fleet-apis.html), since those are generated directly out of the Fleet API spec, we'll need to wait for your https://github.com/elastic/kibana/issues/172155 issue to close, and then I or anyone can regenerate the docs using [these instructions](https://github.com/elastic/ingest-docs/tree/main/docs/en/ingest-management/fleet/api-generated).

**Comment by criamico** [comment]
Thanks @kilfoyle for picking up this ticket! I'll see if https://github.com/elastic/kibana/issues/172155 can get prioritized in one of the upcoming sprints.

**Comment by kilfoyle** [comment]
Just for reference, here's the new docs page: [Required roles and privileges](https://www.elastic.co/guide/en/fleet/current/fleet-roles-and-privileges.html)

**Comment by kilfoyle** [comment]
I think this can be closed, since the public docs are updated and there's a separate PR (https://github.com/elastic/kibana/issues/172155) for the API docs.
