### ISSUE TITLE
Add templates to the repo

### ISSUE THREAD

**Issue by dedemorton** [elastic/ingest-docs#8]
I really like the [new templates](https://github.com/elastic/observability-docs/pull/2231) that Brandon put together. We should add these templates to this repo.

**Comment by bmorelli25** [comment]
Sure! Do you plan on pushing observability-docs to this repository to maintain the history of the files? If so, these templates will transfer as a part of that push.

**Comment by dedemorton** [comment]
> Do you plan on pushing observability-docs to this repository to maintain the history of the files? If so, these templates will transfer as a part of that push.

Not it requires an empty repo. Karen is already working in this repo.

**Comment by dedemorton** [comment]
Old issue...closing....
