### ISSUE TITLE
[REQUEST]: [Fleet] Document workflow for uploading custom integrations

### ISSUE THREAD

**Issue by kpollich** [elastic/ingest-docs#805]
### Description

Since 8.7, Fleet supports integration installation through direct upload as a means to support integration developers or users who have created custom integrations that they don't want to commit upstream back to https://github.com/elastic/integrations. 

We don't document the workflow around uploading a custom integration directly to Kibana outside of our Fleet API docs. We should document this process, and perhaps reference it in our airgapped documentation as well, as airgapped users will find this feature particularly useful in cases where their own self-hosted package registry hasn't been updated to contain a new version of a given integration. 

There are two ways to go about uploading an integration: 
1. Using `elastic-package`, e.g. https://github.com/elastic/elastic-package?tab=readme-ov-file#elastic-package-install
2. Using `cURL` and calling your Kibana API directly

Setting up `elastic-package` is recommended for integration maintainers, generally, as it provides crucial utilities and scripts for building out integrations. So, it's probably reasonable to expect folks developing custom integrations to be able to use it to upload their packages. They'd need to set up `elastic-package` to point at their Kibana cluster then run 

```bash
$ elastic-package install --zip /path/to/my/custom-integration
```

For more info, see https://github.com/elastic/elastic-package/blob/main/docs/howto/install_package.md

Calling the Kibana API directly is also an option, and would manifest as a `cURL`, e.g. 

```bash
$ curl -XPOST -H 'content-type: application/zip' -H 'kbn-xsrf: true' http://your.kibana.host/api/fleet/epm/packages -u {username}:{password} --data-binary @my-custom-integration.zip
```

Let me know if this is enough to get started, and where the docs team thinks these docs belong best. Many thanks!

### Resources

- https://github.com/elastic/kibana/issues/148599
- [OpenAPI docs for install by direct upload API](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/elastic/kibana/main/x-pack/plugins/fleet/common/openapi/bundled.json#/Elastic%20Package%20Manager%20(EPM)/install-package-by-upload) 

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @kpollich

**Stakeholders:** @elastic/fleet

**Comment by kilfoyle** [comment]
@kpollich I think this could go in the Fleet and Agent Guide, but I wonder if it would be a better fit for it to go in the [integrations docs](https://docs.elastic.co/integrations)?  @bmorelli25 What do you think?

**Comment by kilfoyle** [comment]
Ah, I see that we have a [Manage Elastic Agent integrations](https://www.elastic.co/guide/en/fleet/current/integrations.html) section, so I guess that would the ideal spot.

**Comment by bmorelli25** [comment]
I can see a case for either location. I would actually lean toward the integration docs. cc @alaudazzi for her thoughts.

Wherever we decide, we should link from the other.

**Comment by kilfoyle** [comment]
Linking from the Fleet docs (and the [air-gapped environments](https://www.elastic.co/guide/en/fleet/8.11/air-gapped.html) page) to the Integrations docs sounds good to me.

**Comment by alaudazzi** [comment]
@kilfoyle @bmorelli25 sorry for the late reply on this.

If the goal is to document _the workflow around uploading a custom integration directly to Kibana outside of our Fleet API docs_, by looking at the list of user actions in the [Manage Elastic Agent Integrations](https://www.elastic.co/guide/en/fleet/current/integrations.html) section, the most natural place for this workflow seems to be the Fleet and Agent Guide. 
The [integrations docs](https://docs.elastic.co/integrations) are more reference content, a huge list of available integrations where a _how-to_ would be weird. 

I synced over Slack with @kpollich who has kindly offered to provide a quick step-by-step summary of the workflow to be documented.

**Comment by kilfoyle** [comment]
@alaudazzi, @bmorelli25 

I'm happy to document this in the Fleet & Agent Guide if we think that's the best place for it. I just want to be sure we're all agreed about that. Personally, I would think that because this is for developers creating custom integrations, the Integrations Developer Guide would be the best fit.

Brandon, this one seems quite similar to https://github.com/elastic/observability-dev/issues/2506 that we discussed with Nima.

**Comment by kpollich** [comment]
Looking at this again I don't know that there's really much more to add outside of the description. The general need here is to go from a custom integration created by following this guide: https://www.elastic.co/guide/en/integrations-developer/current/build-a-new-integration.html to seeing it show up in Kibana. 

For local development, the `elastic-package stack` spun up by following https://www.elastic.co/guide/en/integrations-developer/current/build-spin-stack.html in the guide above can be targeted with the package upload via `elastic-package install --zip /path/to/my/custom-integration` as above. 

For production deployments, `elastic-package` can either be configured to point at a production Kibana install (not really recommended), or the Kibana API can be used directly, e.g. 

```
$ zip -r my-custom-integration.zip /path/to/my/custom-integration

$ curl -XPOST \
  -H 'content-type: application/zip' \
  -H 'kbn-xsrf: true' \
  http://your.kibana.host/api/fleet/epm/packages \
  -u {username}:{password} \
  --data-binary @my-custom-integration.zip
```

Let me know if this helps with clarification.

**Comment by kilfoyle** [comment]
Thanks @kpollich! I'll just push these changes into the Fleet and Agent Guide then.
