### ISSUE TITLE
Remote Elasticsearch output feature docs are not available

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/ingest-docs#824]
**Description:**
Documentation needs to be updated for Remote Elasticsearch output feature released in 8.12.0.
- Not available under Fleet UI Settings.

![image](https://github.com/elastic/ingest-docs/assets/77374876/e1ad1f55-3cd6-4e88-966f-c8ae72f0bac3)

**Link(s):**
https://www.elastic.co/guide/en/fleet/current/fleet-settings.html

**Screenshot:**
![image](https://github.com/elastic/ingest-docs/assets/77374876/48a0e1f2-1fab-459c-82f4-12edf3fb532e)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by juliaElastic** [comment]
The docs are linked from the Elasticsearch output doc and link to here: https://www.elastic.co/guide/en/fleet/current/monitor-elastic-agent.html#external-elasticsearch-monitoring
<img width="884" alt="image" src="https://github.com/elastic/ingest-docs/assets/90178898/40dac738-cda2-4adf-8813-b51b4b9b8e3f">
