### ISSUE TITLE
[REQUEST]: Document integration assets must be installed in the destination Elasticsaerch cluster when using LS or ES Remote outputs

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/ingest-docs#845]
### Description

Elastic Agent was added the feature to use Logstash output in version 8.2 (Beta) onwards (https://www.elastic.co/guide/en/fleet/8.2/fleet-settings.html#ls-output-settings).
We need to make it clear in the docs when using Logstash output, the destination cluster must have been "prepared" installing the integration assets associated to the policy deployed on the Elastic Agent.

Elastic Agent was added the feature to use Elasticsearch remote output in version 8.12
We need to make it clear in the docs when using Elasticsearch Remote output, the destination cluster must have been "prepared" installing the integration assets associated to the policy deployed on the Elastic Agent.

In both cases, at the moment, there is no way to install the assets automatically given a policy, but this can be done via Fleet UI or via Fleet APIs.

### Resources

N/A

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @nimarezainia, @kilfoyle 

**Stakeholders:** @lucabelluccini

**Comment by kilfoyle** [comment]
Hi @lucabelluccini 
Here's a pull request: https://github.com/elastic/ingest-docs/pull/847

Please let me know if things look okay.
