### ISSUE TITLE
[REQUEST]: Add workaround to Fleet troubleshooting docs

### ISSUE THREAD

**Issue by criamico** [elastic/ingest-docs#897]
### Description

We need to add a common case scenario to Fleet [troubleshooting docs](https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html). 
The issue happens when the user deletes an agent policy associated to inactive agents (as the UI currently allows doing it) and the agent cannot be unenrolled from the UI anymore. Further explanations below.

### Resources

The specific scenario is described [here](https://github.com/elastic/kibana/issues/155925) and the workaround is described in [this comment](https://github.com/elastic/kibana/issues/155925#issuecomment-1919250162). 

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** 

**Stakeholders:**

**Comment by kilfoyle** [comment]
Please see docs PR here: https://github.com/elastic/ingest-docs/pull/903
