### ISSUE TITLE
[REQUEST]: Improve 'Reset the Elastic Cloud policy' step in Fleet Agent migration docs

### ISSUE THREAD

**Issue by gergoabraham** [elastic/ingest-docs#922]
### Description

Docs: https://www.elastic.co/guide/en/fleet/current/migrate-elastic-agent.html#migrate-elastic-agent-reset-policy

When performing Agent migration in [QA console](https://console.qa.cld.elstc.co/home) between two hosted deployments, I experienced two issues regarding the step called `Reset the Elastic Cloud policy`:

1) The step says to open Management -> Dev tools, and paste the given `curl` commands there. However, this does not work properly (I think because headers cannot be set in Dev console), so instead I needed to send the request from a terminal by updating the `curl` command with the precise URL and credentials. I think we should remove the suggestion to use the Dev console as it's misleading.

2) When I performed this step, I had an issue that the Fleet agent disappeared, and Kibana indicated that Fleet is unhealthy.

before and after:
<img width="300px" src="https://github.com/elastic/ingest-docs/assets/39014407/8c7033b3-c82f-4993-8a49-8baaba339c19"/><img width="300px" src="https://github.com/elastic/ingest-docs/assets/39014407/6a36ba42-9d9e-4e99-a61e-2472909df40f"/>

We should include a note, that if the user experiences this issue, they can restart the Integration server of the deployment, and that fixes the problem by enrolling a new Agent for the Cloud Agent policy.

### Resources

here's a slack thread where the workaround for restarting the integration server comes from: https://elastic.slack.com/archives/CNMNXV4RG/p1707207063090799

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @gergoabraham 

**Stakeholders:**

**Comment by kilfoyle** [comment]
Thanks for opening this @gergoabraham! And by the way, your deployment names are making me hungry. :-)

I've opened up https://github.com/elastic/ingest-docs/pull/923 to fix up the docs. Please let me know if I've missed anything.

**Comment by gergoabraham** [comment]
@kilfoyle wow, that was fast. thanks a lot! and sorry for causing hunger 😀
