### ISSUE TITLE
[REQUEST]: Provide additional examples on how to leverage agent_policies overrides

### ISSUE THREAD

**Issue by asmith-elastic** [elastic/ingest-docs#954]
### Description

With the introduction of the following change in 8.9, it is now possible to apply an override to an agent policy. 

https://github.com/elastic/kibana/pull/159414

It would be helpful to have additional documentation around this setting to make it easier to find and understand. One such example could be showing how to override the monitoring port being used, as this is something that user's may need to adjust if an application using the same port is already running on the machine that the agent is deployed to. 

```
PUT kbn:/api/fleet/agent_policies/eba679f0-c76e-11ee-9794-919aa176783b
{
   "name": "Agent policy 1",
   "namespace": "default",
   "overrides": {
       "agent.monitoring.http.port": 6792
   }
}

```

### Resources

This is currently mentioned in the following documentation, but only contains a single example on limiting the CPU. 

https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @asmith-elastic

**Comment by kilfoyle** [comment]
Thanks for this suggestion @asmith-elastic!
I've added a new page with three examples of how to use the custom settings (limiting the amount of CPU consumed by an agent, configuring the agent download timeout, and overriding the default port used for monitoring).

Here's the PR with the changes: https://github.com/elastic/ingest-docs/pull/962
